# -*- coding: utf-8 -*-
"""Manuscript_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bNhzMXr7fWnEHulO8JzWZEdi7vGb7kgL

# ⚙️ **Part 1: Environment Setup**
---
> *Installing necessary libraries (`kaleido`) for high-resolution plot exports. Note: Restart the session after running this cell if needed.*
"""

# RUN THIS FIRST in a separate Colab cell and restart the session
!pip install -U kaleido
!pip install kaleido==0.2.1

"""# 📂 **Part 2: Data Loading & Initial Inspection**
---
> *Importing the processed database (`Processed_database.xlsx`) and inspecting data types, missing values, and the first few rows.*
"""

import pandas as pd

# 1. Load the dataset
# Make sure the file is uploaded to the 'content' folder in Colab
file_path = '/content/Processed_database.xlsx'
df = pd.read_excel(file_path)

# 2. See the first 5 rows and all column names
print("--- First 5 Rows ---")
display(df.head())

# 3. Check data types and missing values
print("\n--- Dataset Info ---")
df.info()

"""# ⏳ **Part 3: Temporal Data Preparation**
---
> *Converting dates and identifying 'Baseline' (Pre-marketing) versus 'Post-marketing Discovery' adverse events based on earliest SmPC dates.*
"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# 1. Convert date columns to datetime
# Note: Using errors='coerce' to handle any non-date strings or placeholders
df['Date Added'] = pd.to_datetime(df['Date Added'], errors='coerce')
df['Reference Date'] = pd.to_datetime(df['Reference Date'], errors='coerce')
df['Year Added'] = df['Date Added'].dt.year

# 2. Identify 'Post-Approval' vs 'Baseline' (Pre-marketing) AEs
# According to your thesis, ~75% are pre-marketing (first SmPC version).
# If the Date Added matches the earliest date for that drug, it's baseline.
df['Earliest_Date'] = df.groupby('Brand_Name')['Date Added'].transform('min')
df['AE_Type'] = np.where(df['Date Added'] == df['Earliest_Date'], 'Baseline (Pre-marketing)', 'Post-marketing Discovery')

print("Data Preparation Complete.")

"""# 📊 **Part 4: Manuscript Figure — Safety Landscape**
---
**A4 Landscape Generation (600 DPI) comprising:**
* **Panel A:** Cumulative Growth
* **Panel B:** Velocity of Safety Discovery
* **Panel C:** Regulatory Drivers
* **Panel D:** "Clean Label" Survival Curve
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import matplotlib.gridspec as gridspec

# --- DATA PRE-PROCESSING ---
# Ensure dates are datetime objects
df['Date Added'] = pd.to_datetime(df['Date Added'], errors='coerce')
df['Launch_Date'] = df.groupby('Brand_Name')['Date Added'].transform('min')

# Calculate "Drug Age" at the time of each AE addition
df['Drug_Age_at_AE'] = (df['Date Added'].dt.year - df['Launch_Date'].dt.year)

# Filter for Post-Marketing only (Age > 0)
vintage_df = df[df['Drug_Age_at_AE'] > 0].copy()

# --- PLOT CONFIGURATION ---
# Setup the figure for A4 Landscape (11.69 x 8.27 inches) at 600 DPI
fig = plt.figure(figsize=(11.69, 8.27))
gs = gridspec.GridSpec(2, 2, figure=fig, hspace=0.4, wspace=0.45)

def add_panel_label(ax, label):
    # Positioning labels in the top-left margin
    ax.text(-0.15, 1.1, label, transform=ax.transAxes,
            fontsize=16, fontweight='bold', va='top', ha='right')

# --- PANEL A: Cumulative Growth ---
ax1 = fig.add_subplot(gs[0, 0])
growth = df.dropna(subset=['Date Added']).groupby(df['Date Added'].dt.year).size().cumsum()
growth.plot(kind='line', marker='o', color='#2c3e50', linewidth=1.5, markersize=3, ax=ax1)
ax1.set_ylabel('Cumulative Drug-AE Pairs', fontsize=10)
ax1.set_xlabel('Year Added to SmPC', fontsize=10)
ax1.grid(True, linestyle='--', alpha=0.4)
ax1.tick_params(labelsize=8)
add_panel_label(ax1, 'A')

# --- PANEL B: Velocity of Safety Discovery ---
ax2 = fig.add_subplot(gs[0, 1])
# Using the previously calculated vintage_df for post-marketing trends
yearly_signals = vintage_df.groupby(vintage_df['Date Added'].dt.year).size()

ax2.plot(yearly_signals.index, yearly_signals.values, marker="o", color="firebrick", linewidth=1.5, markersize=3)
ax2.fill_between(yearly_signals.index, yearly_signals.values, color="firebrick", alpha=0.1)
ax2.set_xlabel('Year of Label Update', fontsize=10)
ax2.set_ylabel('Number of AEs added to SmPC', fontsize=10)
ax2.grid(True, linestyle='--', alpha=0.4)
ax2.tick_params(labelsize=8)
add_panel_label(ax2, 'B')

# --- PANEL C: Regulatory Drivers (Procedure Types) ---
ax3 = fig.add_subplot(gs[1, 0])
procedure_counts = df['Union_register_procedure'].value_counts().head(10)
sns.barplot(x=procedure_counts.values, y=procedure_counts.index, palette='magma', ax=ax3)
ax3.set_xlabel('Number of Drug-AE Associations', fontsize=10)
ax3.set_ylabel('')
ax3.tick_params(axis='y', labelsize=7) # Small font for long procedure strings
ax3.tick_params(axis='x', labelsize=8)
add_panel_label(ax3, 'C')

# --- PANEL D: "Clean Label" Survival Curve ---
ax4 = fig.add_subplot(gs[1, 1])
total_drugs = df['Brand_Name'].nunique()
# Identify the first post-marketing update for each drug
first_update = vintage_df.groupby('Brand_Name')['Drug_Age_at_AE'].min().reset_index()

years = range(0, 21)
cumulative_updates = [first_update[first_update['Drug_Age_at_AE'] <= y]['Brand_Name'].nunique() for y in years]
clean_pct = [(1 - (c / total_drugs)) * 100 for c in cumulative_updates]

ax4.plot(years, clean_pct, marker='o', linestyle='-', color='navy', markersize=4, linewidth=1.5)
ax4.set_xlabel('Years Post-Launch', fontsize=10)
ax4.set_ylabel('% Drugs with No Post-Marketing Updates', fontsize=10)
ax4.set_ylim(0, 105)
ax4.grid(True, linestyle='--', alpha=0.4)
ax4.tick_params(labelsize=8)
add_panel_label(ax4, 'D')

# --- FINAL LAYOUT & SAVE ---
# Adjusting margins to ensure no labels are cut off at 600 DPI
plt.subplots_adjust(left=0.18, right=0.95, top=0.92, bottom=0.1)

# Export for manuscript
plt.savefig('Figure1.png', dpi=600, bbox_inches='tight')
plt.show()

"""# 🌞 **Part 5: Safety Landscape — Stacked Layout & Sunburst**
---
> *Generating a static image from Plotly and integrating it into the matplotlib gridspec layout.*
* **Panel A:** ATC Level 1 Distribution
* **Panel B:** SOC vs Regulatory Updates
* **Panel C:** Specificity "Long Tail"
* **Panel D:** Embedded Original Sunburst
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import matplotlib.gridspec as gridspec
import plotly.express as px
import plotly.io as pio
import io
import matplotlib.image as mpimg

# --- PART 1: PREPARE DATA ---
# Ensure dates and hierarchy data are ready
df['Date Added'] = pd.to_datetime(df['Date Added'], errors='coerce')

# Data for specificity analysis (Panel C)
pt_counts = df.groupby('MedDRA_PT_Term')['Brand_Name'].nunique().reset_index(name='Drug_Count')
def categorize_specificity(count):
    if count == 1: return 'Unique (1)'
    elif count <= 5: return 'Rare (2-5)'
    elif count <= 50: return 'Common (6-50)'
    else: return 'Ubiquitous (>50)'
pt_counts['Category'] = pt_counts['Drug_Count'].apply(categorize_specificity)
category_order = ['Unique (1)', 'Rare (2-5)', 'Common (6-50)', 'Ubiquitous (>50)']

# Data for hierarchy analysis (Panel D)
atc_hier_data = df.dropna(subset=['ATC_Level_1_Desc', 'ATC_Level_2_Desc']).copy()
atc_counts_hier = atc_hier_data.groupby(['ATC_Level_1_Desc', 'ATC_Level_2_Desc']).size().reset_index(name='Count')

# --- PART 2: GENERATE STATIC IMAGE FROM PLOTLY (Panel D) ---
fig_sun = px.sunburst(
    atc_counts_hier,
    path=['ATC_Level_1_Desc', 'ATC_Level_2_Desc'],
    values='Count',
    color='Count',
    color_continuous_scale='RdBu_r',
)
fig_sun.update_layout(margin=dict(t=10, l=10, r=10, b=10))

# Export to bytes using kaleido 0.2.1
img_bytes = pio.to_image(fig_sun, format="png", scale=4)
sunburst_img = mpimg.imread(io.BytesIO(img_bytes))

# --- PART 3: CREATE THE A4 LANDSCAPE MANUSCRIPT FIGURE ---
fig = plt.figure(figsize=(18.39, 12.27))
gs = gridspec.GridSpec(2, 2, figure=fig, hspace=0.35, wspace=0.55)

def add_panel_label(ax, label):
    ax.text(-0.15, 1.1, label, transform=ax.transAxes,
            fontsize=16, fontweight='bold', va='top', ha='right')

# --- PANEL A: ATC Level 1 Distribution (Top Left) ---
ax1 = fig.add_subplot(gs[0, 0])
atc_counts = df['ATC_Level_1_Code'].value_counts().head(15)
sns.barplot(x=atc_counts.values, y=atc_counts.index, palette='viridis', ax=ax1)
ax1.set_xlabel('Number of Drug-AE Pairs', fontsize=10)
ax1.set_ylabel('')
ax1.tick_params(labelsize=8)
add_panel_label(ax1, 'A')

# --- PANEL B: SOC vs Regulatory Updates (Top Right) ---
ax2 = fig.add_subplot(gs[0, 1])
updates_vs_soc = df.groupby(['MedDRA_SOC_Term', 'Source']).size().unstack().fillna(0)
# Re-aligning with specified categories
updates_vs_soc['Total'] = updates_vs_soc.sum(axis=1)
updates_vs_soc = updates_vs_soc.sort_values('Total', ascending=False).head(15).drop('Total', axis=1)

# Plotting stacked bars
updates_vs_soc.plot(kind='barh', stacked=True, color=['#2a9d8f', '#e76f51'], ax=ax2)
ax2.set_xlabel('Number of Drug-AE Pairs', fontsize=10)
ax2.set_ylabel('')
ax2.tick_params(axis='y', labelsize=7)
ax2.legend(title='Discovery Phase', fontsize=8, title_fontsize=9, loc='upper right', frameon=True)
add_panel_label(ax2, 'B')

# --- PANEL C: Specificity "Long Tail" (Bottom Left) ---
ax3 = fig.add_subplot(gs[1, 0])
sns.countplot(data=pt_counts, x='Category', order=category_order, palette='viridis', ax=ax3)
ax3.set_xlabel('Number of Drugs sharing the AE', fontsize=10)
ax3.set_ylabel('Number of Unique MedDRA PTs', fontsize=10)
total_pts = len(pt_counts)
for p in ax3.patches:
    percentage = '{:.1f}%'.format(100 * p.get_height() / total_pts)
    ax3.annotate(percentage, (p.get_x() + p.get_width() / 2, p.get_height() + 20),
                 ha='center', fontsize=9, fontweight='bold')
add_panel_label(ax3, 'C')

# --- PANEL D: EMBEDDED ORIGINAL SUNBURST (Bottom Right) ---
ax4 = fig.add_subplot(gs[1, 1])
ax4.imshow(sunburst_img)
ax4.axis('off')
add_panel_label(ax4, 'D')

# --- FINAL SAVE ---
plt.subplots_adjust(left=0.2, right=0.95, top=0.9, bottom=0.1)
plt.savefig('Figure3.png', dpi=600, bbox_inches='tight')
plt.show()

"""# 🧬 **Part 6: Novelty Analysis & Drug Classification**
---
> *Extracting the first year of appearance for each PT and classifying drugs as Biologic/Targeted vs. Small Molecule based on INN suffixes.*
"""

import pandas as pd
import matplotlib.pyplot as plt

# 1. Prepare Data: Ensure 'Year Added' exists and is valid
# Convert 'Date Added' to datetime if needed, then extract Year
if 'Date Added' in df.columns:
    df['Date Added'] = pd.to_datetime(df['Date Added'], errors='coerce')
    df['Year Added'] = df['Date Added'].dt.year

# Filter out rows with missing Years or PTs
clean_df = df.dropna(subset=['MedDRA_PT_Term', 'Year Added']).copy()

# 2. Analysis: Find the first year each PT appeared
pt_first_year = clean_df.groupby('MedDRA_PT_Term')['Year Added'].min().reset_index(name='First_Seen_Year')

# Count how many *new* PTs were introduced each year
novelty_by_year = pt_first_year.groupby('First_Seen_Year').size().reset_index(name='New_PTs')

# Calculate Cumulative Sum
novelty_by_year['Cumulative_PTs'] = novelty_by_year['New_PTs'].cumsum()

# Classify by INN suffix as a proxy
biologics_keywords = ['mab', 'nib', 'zumab', 'ximab', 'lumab', 'tinib', 'rafenib', 'ciclib']
df['Drug_Type'] = df['inn'].apply(
    lambda x: 'Biologic/Targeted' if any(x.lower().endswith(k) for k in biologics_keywords)
    else 'Small Molecule' if pd.notna(x) else 'Unknown'
)
ae_per_drug = df.groupby('Brand_Name')['MedDRA_PT_Term'].nunique().reset_index(name='AE_Count')
ae_per_drug = ae_per_drug.merge(df[['Brand_Name','ATC_Level_1_Desc']].drop_duplicates(), on='Brand_Name')
soc_per_drug = df.groupby('Brand_Name')['MedDRA_SOC_Term'].nunique().reset_index(name='SOC_Count')
soc_per_drug = soc_per_drug.merge(df[['Brand_Name','ATC_Level_1_Desc']].drop_duplicates(), on='Brand_Name')

"""# 📈 **Part 7: Figure — Novelty and Mechanism**
---
> *Visualizing the introduction of new MedDRA PTs and comparing mechanism-based profiles across drug types.*
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import matplotlib.gridspec as gridspec

# --- Figure 1 Setup ---
fig1 = plt.figure(figsize=(11.69, 8.27))
gs1 = gridspec.GridSpec(2, 1, figure=fig1, hspace=0.3)

def add_panel_label(ax, label):
    ax.text(-0.05, 1.1, label, transform=ax.transAxes, fontsize=18, fontweight='bold', va='top')

# --- PANEL A: Novelty Index (Top) ---
ax1a = fig1.add_subplot(gs1[0, 0])
ax1b = ax1a.twinx()
ax1a.bar(novelty_by_year['First_Seen_Year'], novelty_by_year['New_PTs'], color='steelblue', alpha=0.5)
ax1b.plot(novelty_by_year['First_Seen_Year'], novelty_by_year['Cumulative_PTs'], color='firebrick', linewidth=2, marker='o', markersize=4)

ax1a.set_ylabel('New MedDRA PTs Introduced', color='steelblue', fontsize=12, fontweight='bold')
ax1b.set_ylabel('Cumulative Unique PTs', color='firebrick', fontsize=12, fontweight='bold')
ax1a.set_xlabel('Year of Introduction', fontsize=12)
ax1a.tick_params(labelsize=10)
ax1b.tick_params(labelsize=10)
add_panel_label(ax1a, 'A')

# --- PANEL B: Mechanism-Based Profiles (Bottom) ---
ax2 = fig1.add_subplot(gs1[1, 0])
top_socs = df['MedDRA_SOC_Term'].value_counts().head(12).index
soc_type = df[df['MedDRA_SOC_Term'].isin(top_socs) & df['Drug_Type'].isin(['Biologic/Targeted','Small Molecule'])]
soc_type = soc_type.groupby(['Drug_Type','MedDRA_SOC_Term']).size().reset_index(name='Count')
soc_type['Pct'] = soc_type.groupby('Drug_Type')['Count'].transform(lambda x: x / x.sum() * 100)

sns.barplot(data=soc_type, x='Pct', y='MedDRA_SOC_Term', hue='Drug_Type', palette='Set1', ax=ax2)
ax2.set_xlabel('Percentage of Total AEs within Drug Type (%)', fontsize=12, fontweight='bold')
ax2.set_ylabel('')
ax2.legend(fontsize=10, title='Drug Type', title_fontsize=11, loc='center right')
ax2.tick_params(labelsize=10)
add_panel_label(ax2, 'B')

plt.subplots_adjust(left=0.2, right=0.9, top=0.9, bottom=0.1)
plt.savefig('Figure2.png', dpi=600, bbox_inches='tight')
plt.show()

"""# 📉 **Part 8: Figure — Toxicity Metrics**
---
> *Analyzing the per-drug adverse event burden (Unique PTs) and multi-system toxicity (Distinct SOCs distribution).*
"""

# --- Figure 2 Setup ---
fig2 = plt.figure(figsize=(11.69, 8.27))
gs2 = gridspec.GridSpec(2, 1, figure=fig2, hspace=0.4)

# --- PANEL A: Per-Drug AE Burden (Top) ---
# Nested Grid: Histogram Left, Boxplot Right
inner_gs_a = gridspec.GridSpecFromSubplotSpec(1, 2, subplot_spec=gs2[0, 0], wspace=0.4, width_ratios=[1, 1.4])
ax3h = fig2.add_subplot(inner_gs_a[0, 0])
ax3b = fig2.add_subplot(inner_gs_a[0, 1])

sns.histplot(ae_per_drug['AE_Count'], bins=30, kde=True, ax=ax3h, color='steelblue')
ax3h.axvline(ae_per_drug['AE_Count'].median(), color='red', linestyle='--', linewidth=2)
ax3h.set_xlabel('Unique PTs Distribution', fontsize=11, fontweight='bold')
ax3h.tick_params(labelsize=10)

order_c = ae_per_drug.groupby('ATC_Level_1_Desc')['AE_Count'].median().sort_values().index
sns.boxplot(data=ae_per_drug, y='ATC_Level_1_Desc', x='AE_Count', order=order_c, palette='Set2', ax=ax3b)
ax3b.yaxis.tick_right()
ax3b.set_xlabel('PTs per Drug', fontsize=11, fontweight='bold')
ax3b.set_ylabel('')
ax3b.tick_params(labelsize=9)
add_panel_label(ax3h, 'A')

# --- PANEL B: Multi-System Toxicity (Bottom) ---
# Nested Grid: Histogram Left, Boxplot Right
inner_gs_b = gridspec.GridSpecFromSubplotSpec(1, 2, subplot_spec=gs2[1, 0], wspace=0.4, width_ratios=[1, 1.4])
ax4h = fig2.add_subplot(inner_gs_b[0, 0])
ax4b = fig2.add_subplot(inner_gs_b[0, 1])

sns.histplot(soc_per_drug['SOC_Count'], bins=range(1, 28), discrete=True, ax=ax4h, color='purple')
ax4h.axvline(soc_per_drug['SOC_Count'].median(), color='red', linestyle='--', linewidth=2)
ax4h.set_xlabel('Distinct SOCs Distribution', fontsize=11, fontweight='bold')
ax4h.tick_params(labelsize=10)

order_d = soc_per_drug.groupby('ATC_Level_1_Desc')['SOC_Count'].median().sort_values().index
sns.boxplot(data=soc_per_drug, y='ATC_Level_1_Desc', x='SOC_Count', order=order_d, palette='Purples', ax=ax4b)
ax4b.yaxis.tick_right()
ax4b.set_xlabel('SOCs per Drug', fontsize=11, fontweight='bold')
ax4b.set_ylabel('')
ax4b.tick_params(labelsize=9)
add_panel_label(ax4h, 'B')

plt.subplots_adjust(left=0.1, right=0.82, top=0.9, bottom=0.1)
plt.savefig('Figure4.png', dpi=600, bbox_inches='tight')
plt.show()

"""# 🛡️ **Part 9: Reproducibility — Processed Database**
---
> *Verifying core dataset statistics against the manuscript claims, including total rows, unique CAP products, and temporal range (Data lock point: 15/12/2025).*
"""

# ============================================================
#  DATASET STATISTICS VERIFICATION — Processed_database.xlsx
#  Assumes the file is already at /content/Processed_database.xlsx
# ============================================================

import pandas as pd

# ── 1. Load ────────────────────────────────────────────────
filename = "/content/Processed_database.xlsx"
print(f"⏳ Loading '{filename}' …")
df = pd.read_excel(filename, sheet_name="Sheet1")
df = df.dropna(axis=1, how="all")
print(f"✅ Loaded  →  {len(df):,} rows  ×  {len(df.columns)} columns\n")
print("=" * 65)

# ── 2. Helper ──────────────────────────────────────────────
def check(label, computed, expected, note=""):
    status = "✅ MATCH" if computed == expected else "❌ MISMATCH"
    print(f"\n{status}  |  {label}")
    print(f"   Expected : {expected:,}" if isinstance(expected, int) else f"   Expected : {expected}")
    print(f"   Computed : {computed:,}" if isinstance(computed, int) else f"   Computed : {computed}")
    if computed != expected and isinstance(computed, int):
        print(f"   Diff     : {computed - expected:+,}")
    if note:
        print(f"   Note     : {note}")

# ── 3. Verify each claim ───────────────────────────────────

# ── 3a. Total drug-event associations (rows) ───────────────
total_rows = len(df)
check(
    "Total drug-event associations",
    total_rows,
    110_823,
    note="Total rows in the processed dataset"
)

# ── 3b. Unique CAP products ────────────────────────────────
cap_col = "Union_register_eu_num"
n_cap = df[cap_col].dropna().nunique()
check(
    "Unique CAP products (by EU authorisation number)",
    n_cap,
    1_479,
    note=f"Distinct values in column '{cap_col}'"
)

# ── 3d. Temporal range ─────────────────────────────────────
date_col = "Reference Date"
dates    = pd.to_datetime(df[date_col], errors="coerce").dropna()
earliest = dates.min().date()
latest   = dates.max().date()
span_yrs = (dates.max() - dates.min()).days / 365.25

LOCK_DATE   = pd.Timestamp("2025-12-15").date()
within_lock = latest <= LOCK_DATE

print(f"\n{'✅' if within_lock else '❌'}  Temporal range  |  column: '{date_col}'")
print(f"   Data lock point  : 15/12/2025")
print(f"   Earliest record  : {earliest}")
print(f"   Latest record    : {latest}  "
      f"{'← last analysis run before lock point ✅' if within_lock else '← exceeds lock point ❌'}")
print(f"   Span             : {span_yrs:.1f} years")
print(f"   Expected range   : 01/10/1995 – 15/12/2025  (~30 years)")

# ── 4. Summary table ───────────────────────────────────────
print("\n" + "=" * 65)
print("SUMMARY")
print("=" * 65)
summary = [
    ("Total rows (drug-event associations)", total_rows,   110_823),
    ("Unique CAP products",                  n_cap,          1_479)
]
for label, got, want in summary:
    mark = "✅" if got == want else "❌"
    print(f"  {mark}  {label:<40}  got {got:>7,}  |  expected {want:>7,}")
print("\nDone.")

"""# 🏗️ **Part 10: Reproducibility — Structural Verification**
---
> *Validating feature engineering logic, specifically the proportions of small molecules, ATC classes, and pre- vs. post-marketing percentages.*
"""

# ============================================================
#  DATASET STATISTICS VERIFICATION — Updated Expected Values
# ============================================================

import pandas as pd
import numpy as np

# ── 1. Load Data ───────────────────────────────────────────
file_path = 'Processed_database.xlsx'
print(f"⏳ Loading '{file_path}' …")
df = pd.read_excel(file_path)
print(f"✅ Loaded  →  {len(df):,} rows  ×  {len(df.columns)} columns\n")
print("=" * 65)

# ── 2. Apply Your Feature Engineering ──────────────────────
# A. Define Pre-marketing vs Post-marketing (from your script)
df['Date Added'] = pd.to_datetime(df['Date Added'], errors='coerce')
df['Earliest_Date'] = df.groupby('Brand_Name')['Date Added'].transform('min')
df['AE_Type'] = np.where(df['Date Added'] == df['Earliest_Date'], 'Pre-marketing', 'Post-marketing')

# B. Define Drug Type (Biologic vs Small Molecule from INN)
if 'Drug_Type' not in df.columns and 'inn' in df.columns:
    biologics_keywords = ['mab', 'nib', 'zumab', 'ximab', 'lumab', 'tinib', 'rafenib', 'ciclib']
    df['Drug_Type'] = df['inn'].apply(
        lambda x: 'Biologic/Targeted' if any(str(x).lower().endswith(k) for k in biologics_keywords)
        else 'Small Molecule' if pd.notna(x) else 'Unknown'
    )

# ── 3. Helper Function ─────────────────────────────────────
def check(label, computed, expected, is_pct=False, tolerance=0.2):
    """Validates computed values against expected text claims."""
    if is_pct or isinstance(computed, float):
        match = abs(computed - expected) <= tolerance
        comp_str, exp_str = f"{computed:.1f}%", f"{expected:.1f}%"
    else:
        match = (computed == expected)
        comp_str, exp_str = f"{computed:,}", f"{expected:,}"

    status = "✅ MATCH" if match else "❌ MISMATCH"
    print(f"{status} | {label}")
    print(f"   Expected: {exp_str}  |  Computed: {comp_str}")
    if not match:
        diff = computed - expected
        diff_str = f"{diff:+.1f}%" if is_pct else f"{diff:+,}"
        print(f"   Diff    : {diff_str}")
    print("-" * 50)

# ── 4. Verify Claims ───────────────────────────────────────
print("VERIFYING MANUSCRIPT CLAIMS...\n" + "=" * 65)

# --- Paragraph 1: Small Molecule Proportions ---
if 'Drug_Type' in df.columns:
    small_mols = df[df['Drug_Type'] == 'Small Molecule']
    if not small_mols.empty:
        sm_soc_pct = small_mols['MedDRA_SOC_Term'].value_counts(normalize=True) * 100
        # UPDATED: 14.5 -> 11.3
        check("Small molecules - Gastrointestinal (Proportional burden)",
              sm_soc_pct.get("Gastrointestinal disorders", 0), 11.3, is_pct=True)
        # UPDATED: 13.0 -> 10.0
        check("Small molecules - Nervous system (Proportional burden)",
              sm_soc_pct.get("Nervous system disorders", 0), 10.0, is_pct=True)

# --- Paragraph 2: ATC Classes & Overall SOC & Periods ---

# ATC Associations
atc_counts = df['ATC_Level_1_Desc'].value_counts()
atc_pcts = df['ATC_Level_1_Desc'].value_counts(normalize=True) * 100
target_atc = "Antineoplastic and immunomodulating agents"
check(f"ATC: {target_atc} (Count)", atc_counts.get(target_atc, 0), 48692)

check(f"ATC: {target_atc} (%)", atc_pcts.get(target_atc, 0), 45.2, is_pct=True)

# Overall SOC Associations
soc_counts = df['MedDRA_SOC_Term'].value_counts()
soc_pcts = df['MedDRA_SOC_Term'].value_counts(normalize=True) * 100

check("SOC: Gastrointestinal disorders (Count)", soc_counts.get("Gastrointestinal disorders", 0), 11618)
# UPDATED: 10.5 -> 10.9
check("SOC: Gastrointestinal disorders (%)", soc_pcts.get("Gastrointestinal disorders", 0), 10.9, is_pct=True)
check("SOC: Skin & subcutaneous tissue (Count)", soc_counts.get("Skin and subcutaneous tissue disorders", 0), 9968)
# UPDATED: 9.0 -> 9.3
check("SOC: Skin & subcutaneous tissue (%)", soc_pcts.get("Skin and subcutaneous tissue disorders", 0), 9.3, is_pct=True)
check("SOC: Nervous system disorders (Count)", soc_counts.get("Nervous system disorders", 0), 9926)

# Pre vs Post Marketing
period_counts = df['AE_Type'].value_counts()
period_pcts = df['AE_Type'].value_counts(normalize=True) * 100

check("Period: Pre-marketing (Count)", period_counts.get("Pre-marketing", 0), 82534)
check("Period: Pre-marketing (%)", period_pcts.get("Pre-marketing", 0), 74.6, is_pct=True)

check("Period: Post-marketing (Count)", period_counts.get("Post-marketing", 0), 28289)
check("Period: Post-marketing (%)", period_pcts.get("Post-marketing", 0), 25.4, is_pct=True)

# Unique PT specificity
pt_product_counts = df.groupby('MedDRA_PT_Term')['Brand_Name'].nunique()
single_product_pts = (pt_product_counts == 1).sum()
total_unique_pts = len(pt_product_counts)
pct_single_product_pts = (single_product_pts / total_unique_pts) * 100
check("PTs associated with only a single product (%)", pct_single_product_pts, 21.7, is_pct=True)

# --- Paragraph 3: Per-Drug Statistics ---

# PTs per drug
pts_per_drug = df.groupby('Brand_Name')['MedDRA_PT_Term'].nunique()
check("PTs per drug (Mean)", float(pts_per_drug.mean()), 68.1)
check("PTs per drug (Median)", float(pts_per_drug.median()), 48.0)

# Distinct SOCs per drug
socs_per_drug = df.groupby('Brand_Name')['MedDRA_SOC_Term'].nunique()
check("Distinct SOCs per drug (Median)", float(socs_per_drug.median()), 14.0)

print("\n" + "=" * 65)
print("VERIFICATION COMPLETE")
print("=" * 65)

"""# 🌐 **Part 11: Full Database Acquisition**
---
> *Connecting to Dropbox to download and extract the full global adverse event timeline zip archive.*
"""

import pandas as pd
import os
import glob
import zipfile
import requests
import ast  # Library to safely parse the string representation of lists/dicts

# ==========================================
# 1. CONFIGURATION
# ==========================================
# ⚠️ PASTE YOUR DROPBOX LINK HERE
DROPBOX_LINK = "https://www.dropbox.com/scl/fi/bnlqn4od0r7v9ese6ectr/Database.zip?rlkey=49m75q7qpvq9qye9yyyud1lca&st=fl7o75y4&dl=0"

OUTPUT_FILE = "Global_Adverse_Event_Timeline_Full_Details.xlsx"
LOCAL_EXTRACT_PATH = "/content/DRUGS_DATA/"
ZIP_PATH = "drugs_download.zip"

# ==========================================
# 2. DOWNLOAD & UNZIP DATA
# ==========================================
print("1. SETTING UP DATA...")
download_link = DROPBOX_LINK.replace("dl=0", "dl=1")

try:
    if not os.path.exists(LOCAL_EXTRACT_PATH):
        print("   ⬇️ Downloading from Dropbox...")
        response = requests.get(download_link, stream=True)
        if response.status_code == 200:
            with open(ZIP_PATH, 'wb') as f:
                for chunk in response.iter_content(chunk_size=1024):
                    if chunk: f.write(chunk)
            print(f"   📦 Unzipping to {LOCAL_EXTRACT_PATH}...")
            with zipfile.ZipFile(ZIP_PATH, 'r') as zip_ref:
                zip_ref.extractall(LOCAL_EXTRACT_PATH)
            print("   ✅ Setup complete.\n")
        else:
            raise ConnectionError(f"Dropbox status {response.status_code}")
    else:
        print("   ✅ Data already present. Skipping download.\n")
except Exception as e:
    print(f"\n❌ ERROR: {e}")
    if not os.path.exists(LOCAL_EXTRACT_PATH):
        raise e

"""# 🔍 **Part 12: Raw Data Scanning & Global Statistics**
---
> *Iterating through raw CAP product folders to compute and verify the total number of SmPC versions, drug-event associations, and overarching date ranges.*
"""

# ============================================================
#  RAW DATA STATISTICS VERIFICATION
#  Run AFTER the Dropbox download cell has populated
#  /content/DRUGS_DATA/
# ============================================================

import os, glob, re
import pandas as pd
from tqdm.notebook import tqdm

# ── 1. Locate root ─────────────────────────────────────────
LOCAL_EXTRACT_PATH = "/content/DRUGS_DATA/"

top_level = [
    os.path.join(LOCAL_EXTRACT_PATH, d)
    for d in os.listdir(LOCAL_EXTRACT_PATH)
    if os.path.isdir(os.path.join(LOCAL_EXTRACT_PATH, d))
]
ROOT = top_level[0] if len(top_level) == 1 else LOCAL_EXTRACT_PATH
print(f"📁 Database root : {ROOT}")

# ── 2. Discover drug folders (one folder = one CAP) ────────
drug_folders = sorted([
    os.path.join(ROOT, d)
    for d in os.listdir(ROOT)
    if os.path.isdir(os.path.join(ROOT, d))
])
n_caps = len(drug_folders)
print(f"💊 Drug folders found : {n_caps}\n")

# ── 3. Helper ──────────────────────────────────────────────
def check(label, computed, expected, note=""):
    status = "✅ MATCH" if computed == expected else "❌ MISMATCH"
    print(f"\n{status}  |  {label}")
    print(f"   Expected : {expected:,}")
    print(f"   Computed : {computed:,}")
    if computed != expected:
        print(f"   Diff     : {computed - expected:+,}")
    if note:
        print(f"   Note     : {note}")

DATE_RE = re.compile(r'^(\d{4}-\d{2}-\d{2})_')

# ── 4. Scan all drug folders ───────────────────────────────
print("="*65)
print("SCANNING RAW DATA  (may take a few minutes on the full DB)")
print("="*65)

n_smpc_versions    = 0    # total .txt files across Latest/ + Updates/
all_dates          = []   # SmPC dates from Updates/ filenames
total_associations = 0    # sum of per-drug unique AE count
errors             = []

for drug_path in tqdm(drug_folders, desc="Drugs", unit="drug"):

    # ── SmPC versions: ALL .txt files in Latest/ and Updates/
    txt_files = sorted(
        glob.glob(os.path.join(drug_path, "**", "*.txt"), recursive=True)
    )
    n_smpc_versions += len(txt_files)

    # Dates come from the Updates/ filenames (Latest/ has no date prefix)
    for f in txt_files:
        m = DATE_RE.match(os.path.basename(f))
        if m:
            all_dates.append(pd.Timestamp(m.group(1)))

    # ── Drug-event associations: union of unique AEs across ALL
    #    adverse_events files in both Latest/ and Updates/
    ae_files = sorted(
        glob.glob(os.path.join(drug_path, "**", "*_adverse_events.xlsx"), recursive=True) +
        glob.glob(os.path.join(drug_path, "**", "*_adverse_events.csv"),  recursive=True)
    )

    drug_aes = set()
    for f in ae_files:
        try:
            df = pd.read_excel(f) if f.endswith(".xlsx") else pd.read_csv(f)
            cols = {c.lower(): c for c in df.columns}
            col  = cols.get("adverse_event", df.columns[0])
            aes  = df[col].dropna().astype(str).str.strip().str.upper()
            drug_aes.update(aes[aes.str.len() > 0].tolist())
        except Exception as e:
            errors.append(f"Error reading {f}: {e}")

    total_associations += len(drug_aes)

# ── 5. Verification results ────────────────────────────────
print("\n" + "="*65)
print("VERIFICATION RESULTS")
print("="*65)

# Claim 1 — CAP products
check(
    "CAP products",
    n_caps,
    1_513,
    note="One drug folder = one CAP product"
)

# Claim 2 — SmPC versions
check(
    "SmPC versions",
    n_smpc_versions,
    17_763,
    note="Total .txt files across Latest/ and Updates/ for all drugs"
)

# Claim 3 — Drug-event associations
check(
    "Drug-event associations",
    total_associations,
    125_026,
    note="Per drug: unique AEs across Latest/ + Updates/; then summed"
)

# Claim 4 — Temporal range
if all_dates:
    earliest = min(all_dates).date()
    latest   = max(all_dates).date()
    span_yrs = (max(all_dates) - min(all_dates)).days / 365.25
    LOCK_DATE = pd.Timestamp("2025-12-15").date()
    within_lock = latest <= LOCK_DATE

    print(f"\n{'✅' if within_lock else '❌'}  Temporal range  (from Updates/ filenames)")
    print(f"   Data lock point  : 15/12/2025")
    print(f"   Earliest SmPC    : {earliest}")
    print(f"   Latest SmPC      : {latest}  "
          f"{'← last analysis run before lock point ✅' if within_lock else '← exceeds lock point ❌'}")
    print(f"   Span             : {span_yrs:.1f} years")
    print(f"   Expected range   : 01/10/1995 – 15/12/2025  (~30 years)")


# ── 6. Summary table ───────────────────────────────────────
print("\n" + "="*65)
print("SUMMARY")
print("="*65)
rows = [
    ("CAP products",            n_caps,              1_513),
    ("SmPC versions",           n_smpc_versions,    17_763),
    ("Drug-event associations", total_associations, 125_026),
]
for label, got, want in rows:
    mark = "✅" if got == want else "❌"
    print(f"  {mark}  {label:<35}  got {got:>8,}  |  expected {want:>8,}")

if errors:
    print(f"\n⚠️  {len(errors)} file(s) had issues (first 5):")
    for e in errors[:5]:
        print(f"   • {e}")

print("\n" + "="*65)
print("Done.")

"""# 🔍 **Part 14: Validation dataset Statistics**
---
"""

import zipfile
import os
from google.colab import files

# 1. Trigger the upload dialog to select your ZIP file from your local computer
print("Please select the ZIP file you want to upload:")
uploaded = files.upload()

# 2. Get the name of the uploaded file
zip_file_name = list(uploaded.keys())[0]

# 3. Define the directory where you want to extract the contents
extract_path = "/content/extracted_data/"
os.makedirs(extract_path, exist_ok=True)

# 4. Extract the ZIP file
with zipfile.ZipFile(zip_file_name, 'r') as zip_ref:
    zip_ref.extractall(extract_path)
    print(f"✅ Successfully extracted '{zip_file_name}' to '{extract_path}'")

# 5. List the extracted files to verify
extracted_files = os.listdir(extract_path)
print(f"Total files extracted: {len(extracted_files)}")
print("First 5 files:", extracted_files[:5])

# ============================================================
#  VALIDATION ANALYSIS
#  Computes % correct, duplicate, missing, triplicate
#  across all xlsx files in the validation folder.
#
#  File structure:
#    Col 0 — adverse event term
#    Col 1 — status: correct / duplicate / missing /
#                    missing-r / triplicate
# ============================================================

import os, glob
import pandas as pd
from collections import Counter
from tqdm.notebook import tqdm

# ── 1. Configuration ───────────────────────────────────────
FOLDER = "/content/extracted_data/Validation dataset"   # ← your validation folder

# ── 2. Load all files ──────────────────────────────────────
files = sorted(glob.glob(os.path.join(FOLDER, "*.xlsx")))
print(f"📂 Files found: {len(files)}\n")

# ── 3. Aggregate counts ────────────────────────────────────
VALID_STATUSES = {"correct", "duplicate", "missing", "missing-r", "triplicate"}

total_counter  = Counter()   # global counts
per_drug       = []          # one row per drug for the detail table
no_status_col  = []          # files with only 1 column (no status)
errors         = []

for f in tqdm(files, desc="Reading", unit="file"):
    drug_name = os.path.splitext(os.path.basename(f))[0]
    drug_name = drug_name.replace("_adverse_events", "")

    try:
        df = pd.read_excel(f)

        if len(df.columns) < 2:
            no_status_col.append(drug_name)
            continue

        # Status is always column index 1 regardless of column name
        statuses = (
            df.iloc[:, 1]
            .fillna("")
            .astype(str)
            .str.strip()
            .str.lower()
        )
        # Count only recognised statuses (ignore blanks)
        counts = Counter(s for s in statuses if s in VALID_STATUSES)

        total_counter.update(counts)

        n_total     = sum(counts.values())
        n_correct   = counts.get("correct", 0)
        n_dup       = counts.get("duplicate", 0)
        n_trip      = counts.get("triplicate", 0)
        n_missing   = counts.get("missing", 0) + counts.get("missing-r", 0)
        pct_correct = 100 * n_correct / n_total if n_total > 0 else None

        per_drug.append({
            "Drug":          drug_name,
            "Total":         n_total,
            "Correct":       n_correct,
            "Duplicate":     n_dup,
            "Triplicate":    n_trip,
            "Missing":       n_missing,
            "% Correct":     round(pct_correct, 2) if pct_correct is not None else None,
        })

    except Exception as e:
        errors.append(f"{drug_name}: {e}")

# ── 4. Global summary ──────────────────────────────────────
grand_total   = sum(total_counter.values())
n_correct     = total_counter.get("correct", 0)
n_dup         = total_counter.get("duplicate", 0)
n_trip        = total_counter.get("triplicate", 0)
n_missing     = total_counter.get("missing", 0) + total_counter.get("missing-r", 0)

pct_correct   = 100 * n_correct / grand_total if grand_total else 0
pct_dup       = 100 * n_dup     / grand_total if grand_total else 0
pct_trip      = 100 * n_trip    / grand_total if grand_total else 0
pct_missing   = 100 * n_missing / grand_total if grand_total else 0

print("\n" + "=" * 55)
print("  GLOBAL VALIDATION SUMMARY")
print("=" * 55)
print(f"  Files analysed          : {len(per_drug):>8,}")
print(f"  Files without status col: {len(no_status_col):>8,}")
print(f"  Total AE entries        : {grand_total:>8,}")
print("-" * 55)
print(f"  ✅ Correct              : {n_correct:>8,}   ({pct_correct:.2f}%)")
print(f"  🔁 Duplicate            : {n_dup:>8,}   ({pct_dup:.2f}%)")
print(f"  🔁 Triplicate           : {n_trip:>8,}   ({pct_trip:.2f}%)")
print(f"  ❌ Missing              : {n_missing:>8,}   ({pct_missing:.2f}%)")
print("=" * 55)

if no_status_col:
    print(f"\n⚠️  {len(no_status_col)} files had no status column (skipped):")
    for d in no_status_col[:10]:
        print(f"   • {d}")
    if len(no_status_col) > 10:
        print(f"   … and {len(no_status_col) - 10} more")

if errors:
    print(f"\n❌ {len(errors)} read errors:")
    for e in errors[:5]:
        print(f"   • {e}")

# ── 5. Per-drug detail table ───────────────────────────────
df_detail = (
    pd.DataFrame(per_drug)
    .sort_values("% Correct", ascending=True)   # worst first for easy review
    .reset_index(drop=True)
)

print(f"\n📊 Per-drug table: {len(df_detail)} drugs")
print("   (sorted by % Correct ascending — worst at top)\n")
print(df_detail.to_string(index=False))

# ── 6. Export & download ───────────────────────────────────
OUT = "/content/validation_results.xlsx"

with pd.ExcelWriter(OUT, engine="openpyxl") as writer:
    # Sheet 1: summary
    summary_data = {
        "Metric":  ["Total AE entries", "Correct", "Duplicate",
                    "Triplicate", "Missing", "% Correct",
                    "% Duplicate", "% Triplicate", "% Missing"],
        "Value":   [grand_total, n_correct, n_dup,
                    n_trip, n_missing,
                    round(pct_correct, 2), round(pct_dup, 2),
                    round(pct_trip, 2), round(pct_missing, 2)],
    }
    pd.DataFrame(summary_data).to_excel(writer, sheet_name="Summary", index=False)

    # Sheet 2: per-drug detail
    df_detail.to_excel(writer, sheet_name="Per Drug", index=False)

    # Sheet 3: drugs with no status column
    if no_status_col:
        pd.DataFrame({"Drug (no status col)": no_status_col}).to_excel(
            writer, sheet_name="No Status Col", index=False
        )

print(f"\n💾 Saved: {OUT}")

from google.colab import files
files.download(OUT)
print("📥 Download started.")