# -*- coding: utf-8 -*-
"""SOC_filtering_matching.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pHkrXK_mvoXUyitKWdlw5Ymm1JX3ypH4
"""

!rm -rf /content/*

import pandas as pd
import os
import glob
import zipfile
import requests
import ast  # Library to safely parse the string representation of lists/dicts

# ==========================================
# 1. CONFIGURATION
# ==========================================
# ⚠️ PASTE YOUR DROPBOX LINK HERE
DROPBOX_LINK = "https://www.dropbox.com/scl/fi/d7qe3tkqvv5rd47jihhoh/Database_example.zip?rlkey=0en43a3k5hey9est15wux8epb&st=nkq8xw3o&dl=0"

OUTPUT_FILE = "Global_Adverse_Event_Timeline_Full_Details.xlsx"
LOCAL_EXTRACT_PATH = "/content/DRUGS_DATA/"
ZIP_PATH = "drugs_download.zip"

# ==========================================
# 2. DOWNLOAD & UNZIP DATA
# ==========================================
print("1. SETTING UP DATA...")
download_link = DROPBOX_LINK.replace("dl=0", "dl=1")

try:
    if not os.path.exists(LOCAL_EXTRACT_PATH):
        print("   ⬇️ Downloading from Dropbox...")
        response = requests.get(download_link, stream=True)
        if response.status_code == 200:
            with open(ZIP_PATH, 'wb') as f:
                for chunk in response.iter_content(chunk_size=1024):
                    if chunk: f.write(chunk)
            print(f"   📦 Unzipping to {LOCAL_EXTRACT_PATH}...")
            with zipfile.ZipFile(ZIP_PATH, 'r') as zip_ref:
                zip_ref.extractall(LOCAL_EXTRACT_PATH)
            print("   ✅ Setup complete.\n")
        else:
            raise ConnectionError(f"Dropbox status {response.status_code}")
    else:
        print("   ✅ Data already present. Skipping download.\n")
except Exception as e:
    print(f"\n❌ ERROR: {e}")
    if not os.path.exists(LOCAL_EXTRACT_PATH):
        raise e

import ast
from tqdm.notebook import tqdm  # Progress bar for Jupyter/Colab

# ==========================================
# 1. CONFIGURATION
# ==========================================

OUTPUT_FILE = "Global_Adverse_Event_Timeline_Full_Details.xlsx"
LOCAL_EXTRACT_PATH = "/content/DRUGS_DATA/"

# ==========================================
# 3. ROBUST HELPER FUNCTIONS
# ==========================================
def parse_atc_data(atc_string):
    """
    Safely parses the ATC string. Returns empty dict on ANY failure.
    """
    parsed_data = {}
    for i in range(1, 6):
        parsed_data[f'ATC_Level_{i}_Code'] = ''
        parsed_data[f'ATC_Level_{i}_Desc'] = ''

    # 1. Clean and Validation
    s_data = str(atc_string).strip()
    if s_data == '' or s_data.lower() == 'nan' or s_data == '[]':
        return parsed_data

    try:
        # 2. Attempt Parsing
        # Use ast.literal_eval for safe evaluation of Python-like structures
        data_structure = ast.literal_eval(s_data)

        # Unwrap outer lists (sometimes double nested [[...]])
        if isinstance(data_structure, list):
            while len(data_structure) > 0 and isinstance(data_structure[0], list):
                data_structure = data_structure[0]

            # Extract
            for item in data_structure:
                if isinstance(item, dict):
                    lvl = str(item.get('level', ''))
                    code = item.get('code', '')
                    desc = item.get('description', '')

                    if lvl in ['1', '2', '3', '4', '5']:
                        parsed_data[f'ATC_Level_{lvl}_Code'] = code
                        parsed_data[f'ATC_Level_{lvl}_Desc'] = desc

    except (ValueError, SyntaxError):
        # Allow malformed strings to fail silently without crashing the script
        pass
    except Exception:
        pass

    return parsed_data

# ==========================================
# 4. MAIN PROCESSING LOOP
# ==========================================
print("="*80)
print("STARTING ROBUST PROCESSING LOOP")
print("="*80)

all_findings = []
errors_log = []

# Find drug folders
drug_folders = []
for root, dirs, files in os.walk(LOCAL_EXTRACT_PATH):
    for d in dirs:
        if d.lower() == 'updates':
            drug_folders.append(os.path.dirname(os.path.join(root, d)))

drug_folders = sorted(list(set(drug_folders)))
total_drugs = len(drug_folders)

print(f"Found {total_drugs} drug folders.")

# --- PROGRESS BAR LOOP ---
for drug_path in tqdm(drug_folders, desc="Processing Drugs", unit="drug"):
    brand_name = os.path.basename(drug_path)

    # WRAP EACH DRUG IN TRY/EXCEPT TO PREVENT CRASHING
    try:
        updates_path = os.path.join(drug_path, 'Updates')
        files = glob.glob(os.path.join(updates_path, "*.xlsx"))
        files.sort()

        if not files:
            continue

        # --- A. Baseline ---
        baseline_file = files[0]
        baseline_date = os.path.basename(baseline_file).split('_')[0]

        baseline_df = pd.read_excel(baseline_file)
        # Find column case-insensitively
        cols_map = {c.lower(): c for c in baseline_df.columns}

        if 'adverse_event' not in cols_map:
            errors_log.append(f"{brand_name}: Baseline missing 'adverse_event' column")
            continue

        evt_col = cols_map['adverse_event']
        known_events = set(baseline_df[evt_col].dropna().astype(str).str.strip().str.upper())

        # --- B. Updates ---
        for file_path in files[1:]:
            filename = os.path.basename(file_path)
            current_date = filename.split('_')[0]

            try:
                current_df = pd.read_excel(file_path)
                curr_cols_map = {c.lower(): c for c in current_df.columns}

                if 'adverse_event' not in curr_cols_map:
                    continue

                curr_evt_col = curr_cols_map['adverse_event']
                curr_atc_col = curr_cols_map.get('atc') # Might be None

                for _, row in current_df.iterrows():
                    raw_event = str(row[curr_evt_col]).strip()
                    norm_event = raw_event.upper()

                    if norm_event not in known_events and norm_event != 'NAN' and norm_event != '':

                        # 1. Base Data (retains original columns)
                        finding_entry = row.to_dict()

                        # 2. Metadata
                        finding_entry['Reference Date'] = baseline_date
                        finding_entry['Date Added'] = current_date
                        finding_entry['Brand_Name'] = brand_name
                        finding_entry['Adverse Event'] = raw_event

                        # 3. ATC Parsing (Robust)
                        if curr_atc_col and not pd.isna(row[curr_atc_col]):
                            atc_parsed = parse_atc_data(row[curr_atc_col])
                        else:
                            atc_parsed = parse_atc_data('') # Returns empty structure

                        finding_entry.update(atc_parsed)

                        all_findings.append(finding_entry)
                        known_events.add(norm_event)

            except Exception as e:
                # Log file error but continue drug
                pass

    except Exception as e:
        # Log drug error but continue loop
        errors_log.append(f"{brand_name}: CRASHED - {str(e)}")

# ==========================================
# 5. PROCESS EVALUATION & SAVING
# ==========================================
print("\n" + "="*80)
print("PROCESS EVALUATION")
print("="*80)
print(f"Total Drugs Scanned: {total_drugs}")
print(f"Total New Events Found: {len(all_findings)}")
print(f"Drugs with Errors: {len(errors_log)}")

if errors_log:
    print("\n⚠️ Failed Drugs (First 5):")
    for err in errors_log[:5]:
        print(f"   - {err}")
    if len(errors_log) > 5:
        print(f"   ... and {len(errors_log)-5} more.")

if all_findings:
    print("\nSaving Data...")
    final_df = pd.DataFrame(all_findings)

    # Reorder
    priority_cols = ['Reference Date', 'Date Added', 'Brand_Name', 'Adverse Event', 'inn']
    atc_cols = [f'ATC_Level_{i}_{s}' for i in range(1,6) for s in ['Code', 'Desc']]

    existing_p = [c for c in priority_cols if c in final_df.columns]
    existing_a = [c for c in atc_cols if c in final_df.columns]
    remaining = [c for c in final_df.columns if c not in existing_p and c not in existing_a]

    final_df = final_df[existing_p + existing_a + remaining]

    final_df.to_excel(OUTPUT_FILE, index=False)
    print(f"✅ SUCCESS! Saved to: {OUTPUT_FILE}")

    try:
        from google.colab import files
        files.download(OUTPUT_FILE)
    except:
        pass
else:
    print("❌ No findings to save.")

import pandas as pd
import os
import glob
import zipfile
import requests
import time
import json
import ast
import pickle
from collections import defaultdict
from tqdm.notebook import tqdm
from datetime import datetime

# ==========================================
# CONFIGURATION (USE DEEPSEEK)
# ==========================================
API_KEY = "YOUR_API_KEY_FOR_DEEPSEEK"
MEDDRA_ZIP_PATH = '/content/meddra.zip'
LOCAL_EXTRACT_PATH = "/content/DRUGS_DATA/"
OUTPUT_FILE = "Global_Drug_Safety_Complete_with_MedDRA.xlsx"
UNIQUE_EVENTS_FILE = "Unique_Adverse_Events_MedDRA_Coded.xlsx"

# CHECKPOINT FILES
CHECKPOINT_DIR = "/content/checkpoints/"
EVENTS_CHECKPOINT = os.path.join(CHECKPOINT_DIR, "all_events.pkl")
CODING_CHECKPOINT = os.path.join(CHECKPOINT_DIR, "coding_results.pkl")
SOC_PREDICTION_CHECKPOINT = os.path.join(CHECKPOINT_DIR, "soc_predictions.pkl")
PROGRESS_LOG = os.path.join(CHECKPOINT_DIR, "progress.json")

os.makedirs(CHECKPOINT_DIR, exist_ok=True)

print("="*80)
print("GLOBAL DRUG SAFETY ANALYSIS - ULTRA-OPTIMIZED WITH SOC FILTERING")
print("Clinical Trial Baseline + Post-Approval Events with MedDRA Coding")
print("="*80)

# ==========================================
# CHECKPOINT MANAGEMENT
# ==========================================
def save_checkpoint(data, checkpoint_file, description=""):
    try:
        with open(checkpoint_file, 'wb') as f:
            pickle.dump(data, f)
        print(f"   💾 Checkpoint saved: {description}")
        return True
    except Exception as e:
        print(f"   ⚠️  Failed to save checkpoint: {e}")
        return False

def load_checkpoint(checkpoint_file):
    try:
        if os.path.exists(checkpoint_file):
            with open(checkpoint_file, 'rb') as f:
                return pickle.load(f)
        return None
    except Exception as e:
        print(f"   ⚠️  Failed to load checkpoint: {e}")
        return None

def save_progress(step, description, data=None):
    try:
        progress = {
            'timestamp': datetime.now().isoformat(),
            'step': step,
            'description': description
        }
        if data:
            progress.update(data)
        with open(PROGRESS_LOG, 'w') as f:
            json.dump(progress, f, indent=2)
        return True
    except:
        return False

# Check for existing progress
resume_from_checkpoint = True
previous_progress = load_checkpoint(PROGRESS_LOG)

# ==========================================
# 1. LOAD MEDDRA DICTIONARY
# ==========================================
print("\n1. LOADING MEDDRA DICTIONARY...")

if not os.path.exists(MEDDRA_ZIP_PATH):
    raise FileNotFoundError("MedDRA zip file not found!")

pt_names = {}
hlt_names = {}
hlgt_names = {}
soc_names = {}
pt_to_hlt = {}
hlt_to_hlgt = {}
hlgt_to_soc = {}

# NEW: Build reverse mapping - SOC to PTs
soc_to_pts = defaultdict(list)

with zipfile.ZipFile(MEDDRA_ZIP_PATH, 'r') as z:

    def load_asc(filename_suffix, usecols):
        f_name = next((f for f in z.namelist()
                      if f.endswith('/' + filename_suffix) or f == filename_suffix), None)
        if f_name:
            df = pd.read_csv(z.open(f_name), sep='$', header=None, dtype=str, encoding='ascii', usecols=usecols)
            for col in df.columns:
                df[col] = df[col].str.strip()
            return df
        return pd.DataFrame()

    df = load_asc('pt.asc', [0, 1])
    if not df.empty:
        pt_names = dict(zip(df[0], df[1]))
        pt_names_list = list(pt_names.values())
        pt_name_to_code = {v.upper(): k for k, v in pt_names.items()}
        print(f"   ✓ {len(pt_names)} PTs")

    df = load_asc('hlt.asc', [0, 1])
    if not df.empty:
        hlt_names = dict(zip(df[0], df[1]))
        print(f"   ✓ {len(hlt_names)} HLTs")

    df = load_asc('hlgt.asc', [0, 1])
    if not df.empty:
        hlgt_names = dict(zip(df[0], df[1]))
        print(f"   ✓ {len(hlgt_names)} HLGTs")

    df = load_asc('soc.asc', [0, 1])
    if not df.empty:
        soc_names = dict(zip(df[0], df[1]))
        print(f"   ✓ {len(soc_names)} SOCs")

    df = load_asc('hlt_pt.asc', [0, 1])
    if not df.empty:
        pt_to_hlt = dict(zip(df[1], df[0]))
        print(f"   ✓ {len(pt_to_hlt)} PT→HLT links")

    df = load_asc('hlgt_hlt.asc', [0, 1])
    if not df.empty:
        hlt_to_hlgt = dict(zip(df[1], df[0]))
        print(f"   ✓ {len(hlt_to_hlgt)} HLT→HLGT links")

    df = load_asc('soc_hlgt.asc', [0, 1])
    if not df.empty:
        hlgt_to_soc = dict(zip(df[1], df[0]))
        print(f"   ✓ {len(hlgt_to_soc)} HLGT→SOC links")

# Build SOC → PT mapping
print("\n   🔗 Building SOC → PT mapping...")
for pt_code, pt_name in pt_names.items():
    # Traverse hierarchy: PT → HLT → HLGT → SOC
    hlt_code = pt_to_hlt.get(pt_code)
    if hlt_code:
        hlgt_code = hlt_to_hlgt.get(hlt_code)
        if hlgt_code:
            soc_code = hlgt_to_soc.get(hlgt_code)
            if soc_code:
                soc_to_pts[soc_code].append(pt_name)

# Print SOC statistics
print(f"   ✓ Mapped PTs to SOCs:")
for soc_code, pts in sorted(soc_to_pts.items(), key=lambda x: len(x[1]), reverse=True)[:5]:
    soc_name = soc_names.get(soc_code, "Unknown")
    print(f"      • {soc_name}: {len(pts)} PTs")

print(f"   ✅ MedDRA loaded successfully!")

# ==========================================
# 2. ATC PARSING HELPER
# ==========================================
def parse_atc_data(atc_string):
    """Safely parses the ATC string."""
    parsed_data = {}
    for i in range(1, 6):
        parsed_data[f'ATC_Level_{i}_Code'] = ''
        parsed_data[f'ATC_Level_{i}_Desc'] = ''

    s_data = str(atc_string).strip()
    if s_data == '' or s_data.lower() == 'nan' or s_data == '[]':
        return parsed_data

    try:
        data_structure = ast.literal_eval(s_data)

        if isinstance(data_structure, list):
            while len(data_structure) > 0 and isinstance(data_structure[0], list):
                data_structure = data_structure[0]

            for item in data_structure:
                if isinstance(item, dict):
                    lvl = str(item.get('level', ''))
                    code = item.get('code', '')
                    desc = item.get('description', '')

                    if lvl in ['1', '2', '3', '4', '5']:
                        parsed_data[f'ATC_Level_{lvl}_Code'] = code
                        parsed_data[f'ATC_Level_{lvl}_Desc'] = desc

    except:
        pass

    return parsed_data

# ==========================================
# 3. COLLECT ALL ADVERSE EVENTS
# ==========================================
print("\n2. SCANNING ALL DRUG FOLDERS...")

all_events = None
if resume_from_checkpoint:
    all_events = load_checkpoint(EVENTS_CHECKPOINT)
    if all_events:
        print(f"   ✅ Resumed from checkpoint: {len(all_events)} events loaded")

if all_events is None:
    drug_folders = []
    for root, dirs, files in os.walk(LOCAL_EXTRACT_PATH):
        for d in dirs:
            if d.lower() == 'updates':
                drug_folders.append(os.path.dirname(os.path.join(root, d)))

    drug_folders = sorted(list(set(drug_folders)))
    total_drugs = len(drug_folders)
    print(f"   ✓ Found {total_drugs} drug folders")

    all_events = []
    errors_log = []

    for drug_path in tqdm(drug_folders, desc="   Scanning drugs", unit="drug"):
        brand_name = os.path.basename(drug_path)

        try:
            updates_path = os.path.join(drug_path, 'Updates')
            files = glob.glob(os.path.join(updates_path, "*.xlsx"))
            files.sort()

            if not files:
                continue

            baseline_file = files[0]
            baseline_date = os.path.basename(baseline_file).split('_')[0]

            try:
                baseline_df = pd.read_excel(baseline_file)
                cols_map = {c.lower(): c for c in baseline_df.columns}

                if 'adverse_event' not in cols_map:
                    errors_log.append(f"{brand_name}: Missing 'adverse_event' column")
                    continue

                evt_col = cols_map['adverse_event']
                atc_col = cols_map.get('atc')

                for _, row in baseline_df.iterrows():
                    raw_event = str(row[evt_col]).strip()
                    norm_event = raw_event.upper()

                    if norm_event != 'NAN' and norm_event != '':
                        baseline_entry = row.to_dict()
                        baseline_entry['Reference Date'] = baseline_date
                        baseline_entry['Date Added'] = baseline_date
                        baseline_entry['Brand_Name'] = brand_name
                        baseline_entry['Adverse Event'] = raw_event
                        baseline_entry['Event_Source'] = 'Clinical Trial (Baseline)'

                        if atc_col and not pd.isna(row[atc_col]):
                            atc_parsed = parse_atc_data(row[atc_col])
                        else:
                            atc_parsed = parse_atc_data('')

                        baseline_entry.update(atc_parsed)
                        all_events.append(baseline_entry)

                known_events = set(baseline_df[evt_col].dropna().astype(str).str.strip().str.upper())

            except Exception as e:
                errors_log.append(f"{brand_name}: Baseline error - {str(e)}")
                continue

            for file_path in files[1:]:
                filename = os.path.basename(file_path)
                current_date = filename.split('_')[0]

                try:
                    current_df = pd.read_excel(file_path)
                    curr_cols_map = {c.lower(): c for c in current_df.columns}

                    if 'adverse_event' not in curr_cols_map:
                        continue

                    curr_evt_col = curr_cols_map['adverse_event']
                    curr_atc_col = curr_cols_map.get('atc')

                    for _, row in current_df.iterrows():
                        raw_event = str(row[curr_evt_col]).strip()
                        norm_event = raw_event.upper()

                        if norm_event not in known_events and norm_event != 'NAN' and norm_event != '':
                            post_entry = row.to_dict()
                            post_entry['Reference Date'] = baseline_date
                            post_entry['Date Added'] = current_date
                            post_entry['Brand_Name'] = brand_name
                            post_entry['Adverse Event'] = raw_event
                            post_entry['Event_Source'] = 'Post-Approval Discovery'

                            if curr_atc_col and not pd.isna(row[curr_atc_col]):
                                atc_parsed = parse_atc_data(row[curr_atc_col])
                            else:
                                atc_parsed = parse_atc_data('')

                            post_entry.update(atc_parsed)

                            all_events.append(post_entry)
                            known_events.add(norm_event)

                except Exception:
                    pass

        except Exception as e:
            errors_log.append(f"{brand_name}: {str(e)}")

    baseline_count = sum(1 for e in all_events if e['Event_Source'] == 'Clinical Trial (Baseline)')
    post_count = sum(1 for e in all_events if e['Event_Source'] == 'Post-Approval Discovery')

    print(f"\n   ✓ Found {len(all_events)} total events:")
    print(f"      • {baseline_count} baseline (clinical trial) events")
    print(f"      • {post_count} post-approval events")

    save_checkpoint(all_events, EVENTS_CHECKPOINT, f"{len(all_events)} events collected")
    save_progress("events_collected", f"Collected {len(all_events)} events")

    # STRATEGIC DOWNLOAD: Save events checkpoint (critical!)
    try:
        from google.colab import files
        checkpoint_size_mb = os.path.getsize(EVENTS_CHECKPOINT) / (1024 * 1024)
        print(f"\n   📥 STRATEGIC DOWNLOAD: Events checkpoint ({checkpoint_size_mb:.1f} MB)")
        print(f"   ⚠️  IMPORTANT: This allows resume if runtime disconnects!")
        files.download(EVENTS_CHECKPOINT)
        print(f"   ✅ Checkpoint downloaded! Keep this file safe.")
    except:
        print(f"\n   💡 Checkpoint saved locally: {EVENTS_CHECKPOINT}")

# ==========================================
# 4. SOC PREDICTION FOR UNIQUE EVENTS
# ==========================================
print("\n3. EXTRACTING UNIQUE EVENTS & PREDICTING SOCs...")

unique_events = list(set([e['Adverse Event'] for e in all_events]))
print(f"   ✓ {len(unique_events)} unique adverse events found")

# Check if we have SOC predictions from checkpoint
soc_predictions = None
if resume_from_checkpoint:
    soc_predictions = load_checkpoint(SOC_PREDICTION_CHECKPOINT)
    if soc_predictions:
        print(f"   ✅ Loaded SOC predictions for {len(soc_predictions)} events")

if soc_predictions is None:
    soc_predictions = {}

def predict_socs_batch(terms_to_predict, batch_size=100):
    """Predict likely SOCs for each adverse event term"""

    results = {}

    # Load existing predictions
    results.update(soc_predictions)

    # Filter terms that need prediction
    terms_needing_prediction = [t for t in terms_to_predict if t not in results]

    if not terms_needing_prediction:
        print("   ✅ All SOCs already predicted!")
        return results

    print(f"\n   🎯 Predicting SOCs for {len(terms_needing_prediction)} events...")
    print(f"   Strategy: {batch_size} terms per batch")

    # Get SOC list
    soc_list = [f"{code}: {name}" for code, name in soc_names.items()]
    soc_list_str = "\n".join([f"{i+1}. {soc}" for i, soc in enumerate(soc_list)])

    url = "https://api.deepseek.com/chat/completions"
    headers = {"Authorization": f"Bearer {API_KEY}", "Content-Type": "application/json"}

    total_batches = (len(terms_needing_prediction) + batch_size - 1) // batch_size

    for batch_idx in range(0, len(terms_needing_prediction), batch_size):
        batch_terms = terms_needing_prediction[batch_idx:batch_idx + batch_size]
        batch_num = batch_idx // batch_size + 1

        print(f"   📋 SOC Prediction Batch {batch_num}/{total_batches} ({len(batch_terms)} terms)...", end=' ')

        terms_str = "\n".join([f"• {term}" for term in batch_terms])

        prompt = f"""You are a medical expert. For each adverse event term below, predict the 1-3 most likely MedDRA System Organ Classes (SOCs) it belongs to.

ADVERSE EVENT TERMS ({len(batch_terms)} terms):
{terms_str}

AVAILABLE SOCs (27 total):
{soc_list_str}

Instructions:
1. For each term, predict 1-3 most likely SOCs (use SOC codes like "10017947")
2. Most events belong to 1 SOC, some may span 2-3 SOCs
3. Return a JSON object:

{{
  "Adverse Event 1": ["10017947", "10019805"],
  "Adverse Event 2": ["10021881"],
  "Adverse Event 3": []
}}

Use EXACT term as key, and SOC CODES as values.
If uncertain, include top 2-3 likely SOCs.
"""

        try:
            time.sleep(0.4)
            resp = requests.post(url, headers=headers, json={
                "model": "deepseek-chat",
                "temperature": 0,
                "messages": [{"role": "user", "content": prompt}]
            })

            if resp.status_code == 200:
                llm_response = resp.json()["choices"][0]["message"]["content"].strip()

                try:
                    if "```" in llm_response:
                        llm_response = llm_response.split("```")[1]
                        if llm_response.startswith("json"):
                            llm_response = llm_response[4:]

                    batch_results = json.loads(llm_response)

                    for term, soc_codes in batch_results.items():
                        if isinstance(soc_codes, list):
                            # Validate SOC codes
                            valid_codes = [c for c in soc_codes if c in soc_names]
                            if valid_codes:
                                results[term] = valid_codes
                            else:
                                # Fallback: use all SOCs
                                results[term] = list(soc_names.keys())
                        else:
                            results[term] = list(soc_names.keys())

                    print(f"✓ Predicted")

                except json.JSONDecodeError:
                    print(f"Parse error - using all SOCs")
                    for term in batch_terms:
                        results[term] = list(soc_names.keys())
            else:
                print(f"API error - using all SOCs")
                for term in batch_terms:
                    results[term] = list(soc_names.keys())

        except Exception:
            print(f"Error - using all SOCs")
            for term in batch_terms:
                results[term] = list(soc_names.keys())

        # Checkpoint every 5 batches
        if batch_num % 5 == 0:
            save_checkpoint(results, SOC_PREDICTION_CHECKPOINT,
                          f"SOC predictions for {len(results)} events")

    # Final checkpoint
    save_checkpoint(results, SOC_PREDICTION_CHECKPOINT, f"All {len(results)} SOC predictions")

    # STRATEGIC DOWNLOAD: Save SOC predictions
    try:
        from google.colab import files
        checkpoint_size_mb = os.path.getsize(SOC_PREDICTION_CHECKPOINT) / (1024 * 1024)
        print(f"\n   📥 STRATEGIC DOWNLOAD: SOC predictions ({checkpoint_size_mb:.1f} MB)")
        files.download(SOC_PREDICTION_CHECKPOINT)
        print(f"   ✅ SOC predictions downloaded!")
    except:
        pass

    return results

# Predict SOCs for all unique events
soc_predictions = predict_socs_batch(unique_events)

# Calculate reduction statistics
total_pts = len(pt_names)
reductions = []
for term, soc_codes in soc_predictions.items():
    # Count PTs in predicted SOCs
    pts_in_socs = set()
    for soc_code in soc_codes:
        pts_in_socs.update(soc_to_pts.get(soc_code, []))
    reduction = 100 * (1 - len(pts_in_socs) / total_pts)
    reductions.append(reduction)

avg_reduction = sum(reductions) / len(reductions) if reductions else 0
print(f"\n   📊 SOC Filtering Statistics:")
print(f"      • Average PT reduction: {avg_reduction:.1f}%")
print(f"      • Search space: {total_pts} → ~{int(total_pts * (1 - avg_reduction/100))} PTs")

# ==========================================
# 5. CODE WITH SOC-FILTERED PTS
# ==========================================
print("\n4. CODING EVENTS WITH SOC-FILTERED PTS...")

coding_results = None
if resume_from_checkpoint:
    coding_results = load_checkpoint(CODING_CHECKPOINT)
    if coding_results:
        print(f"   ✅ Resumed: {len(coding_results)} events already coded")

if coding_results is None:
    coding_results = {}

def batch_code_with_soc_filter(terms_to_code, soc_predictions, existing_results=None, term_batch_size=50):
    """Code terms using SOC-filtered PT lists"""

    if existing_results is None:
        existing_results = {}

    results = existing_results.copy()
    term_candidates = defaultdict(list)

    # Step 1: Exact matches
    print(f"\n   📋 Checking for exact matches...")
    terms_needing_search = []
    exact_count = 0

    for term in terms_to_code:
        if term in results:
            continue

        clean_term = term.upper().strip()
        if clean_term in pt_name_to_code:
            results[term] = (pt_name_to_code[clean_term], "Exact Match")
            exact_count += 1
        else:
            terms_needing_search.append(term)

    print(f"   → {exact_count} exact matches, {len(terms_needing_search)} need LLM search")

    if exact_count > 0:
        save_checkpoint(results, CODING_CHECKPOINT, f"{len(results)} events coded")

    if not terms_needing_search:
        return results

    # Step 2: SOC-filtered search
    print(f"\n   🔍 Coding with SOC-filtered PTs...")
    print(f"   Strategy: {term_batch_size} terms at a time, SOC-specific PTs only")

    url = "https://api.deepseek.com/chat/completions"
    headers = {"Authorization": f"Bearer {API_KEY}", "Content-Type": "application/json"}

    total_term_batches = (len(terms_needing_search) + term_batch_size - 1) // term_batch_size

    for term_batch_idx in range(0, len(terms_needing_search), term_batch_size):
        term_batch = terms_needing_search[term_batch_idx:term_batch_idx + term_batch_size]
        batch_num = term_batch_idx // term_batch_size + 1

        print(f"\n   📋 Term Batch {batch_num}/{total_term_batches} ({len(term_batch)} terms):")

        # Group terms by their predicted SOCs for efficient batching
        for term in term_batch:
            predicted_socs = soc_predictions.get(term, list(soc_names.keys()))

            # Get PTs for these SOCs
            relevant_pts = set()
            for soc_code in predicted_socs:
                relevant_pts.update(soc_to_pts.get(soc_code, []))

            relevant_pts_list = list(relevant_pts)

            print(f"      • {term[:40]:40} → {len(relevant_pts_list):5} PTs ({100*len(relevant_pts_list)/total_pts:5.1f}%)", end=' ')

            # If very few PTs, do direct match
            if len(relevant_pts_list) <= 50:
                pt_list_str = "\n".join([f"{i+1}. {pt}" for i, pt in enumerate(relevant_pts_list)])

                prompt = f"""Find the best matching MedDRA PT for this adverse event term.

Adverse Event: "{term}"

Available PTs ({len(relevant_pts_list)} from predicted SOCs):
{pt_list_str}

Return the SINGLE BEST matching PT name, or "NO MATCH" if none fit.
Return ONLY the PT name, nothing else.
"""

                try:
                    time.sleep(0.3)
                    resp = requests.post(url, headers=headers, json={
                        "model": "deepseek-chat",
                        "temperature": 0,
                        "messages": [{"role": "user", "content": prompt}]
                    })

                    if resp.status_code == 200:
                        match = resp.json()["choices"][0]["message"]["content"].strip().replace('"', '')

                        if match.upper() in pt_name_to_code:
                            results[term] = (pt_name_to_code[match.upper()], "SOC-Filtered Match")
                            print("✓")
                        else:
                            # Try fuzzy match
                            for pt in relevant_pts_list:
                                if pt.upper() in pt_name_to_code:
                                    results[term] = (pt_name_to_code[pt.upper()], "SOC-Filtered Match")
                                    print("✓ (fuzzy)")
                                    break
                            else:
                                results[term] = (list(pt_name_to_code.values())[0], "No Match")
                                print("✗")
                    else:
                        results[term] = (list(pt_name_to_code.values())[0], "API Error")
                        print("✗ API")
                except:
                    results[term] = (list(pt_name_to_code.values())[0], "Error")
                    print("✗ Err")
            else:
                # Larger PT list - batch search
                pt_list_str = "\n".join([f"{i+1}. {pt}" for i, pt in enumerate(relevant_pts_list[:300])])

                prompt = f"""Find the top 3 best matching MedDRA PTs for this adverse event term.

Adverse Event: "{term}"

Available PTs ({min(300, len(relevant_pts_list))} from predicted SOCs):
{pt_list_str}

Return a JSON array with the top 3 matching PT names:
["PT match 1", "PT match 2", "PT match 3"]

Or empty array [] if no good matches.
"""

                try:
                    time.sleep(0.3)
                    resp = requests.post(url, headers=headers, json={
                        "model": "deepseek-chat",
                        "temperature": 0,
                        "messages": [{"role": "user", "content": prompt}]
                    })

                    if resp.status_code == 200:
                        llm_response = resp.json()["choices"][0]["message"]["content"].strip()

                        try:
                            if "```" in llm_response:
                                llm_response = llm_response.split("```")[1]
                                if llm_response.startswith("json"):
                                    llm_response = llm_response[4:]

                            candidates = json.loads(llm_response)

                            if isinstance(candidates, list) and len(candidates) > 0:
                                best_match = candidates[0]
                                if best_match.upper() in pt_name_to_code:
                                    results[term] = (pt_name_to_code[best_match.upper()], "SOC-Filtered Batch Match")
                                    print("✓")
                                else:
                                    results[term] = (list(pt_name_to_code.values())[0], "No Match")
                                    print("✗")
                            else:
                                results[term] = (list(pt_name_to_code.values())[0], "No Match")
                                print("✗")
                        except:
                            results[term] = (list(pt_name_to_code.values())[0], "Parse Error")
                            print("✗ Parse")
                    else:
                        results[term] = (list(pt_name_to_code.values())[0], "API Error")
                        print("✗ API")
                except:
                    results[term] = (list(pt_name_to_code.values())[0], "Error")
                    print("✗ Err")

        # Checkpoint every 10 batches
        if batch_num % 10 == 0 or batch_num == total_term_batches:
            save_checkpoint(results, CODING_CHECKPOINT,
                          f"{len(results)}/{len(terms_to_code)} events coded (batch {batch_num})")

            # STRATEGIC DOWNLOAD: Every 10 batches download progress
            if batch_num % 10 == 0:
                try:
                    from google.colab import files
                    checkpoint_size_mb = os.path.getsize(CODING_CHECKPOINT) / (1024 * 1024)
                    print(f"\n      📥 Downloading checkpoint ({checkpoint_size_mb:.1f} MB)...", end=' ')
                    files.download(CODING_CHECKPOINT)
                    print(f"✅")
                except:
                    pass

    # Final checkpoint
    save_checkpoint(results, CODING_CHECKPOINT, f"All {len(results)} events coded (COMPLETE)")
    save_progress("coding_complete", f"Coded all {len(results)} events")

    return results

# Code with SOC filtering
if len(unique_events) > len(coding_results):
    coding_results = batch_code_with_soc_filter(unique_events, soc_predictions, coding_results)

# ==========================================
# REST OF THE SCRIPT (SAME AS BEFORE)
# ==========================================
print("\n5. BUILDING MEDDRA HIERARCHY...")

meddra_lookup = {}
for term, (pt_code, method) in coding_results.items():
    pt_desc = pt_names.get(pt_code, "Unknown PT")
    hlt_code = pt_to_hlt.get(pt_code)
    hlt_desc = hlt_names.get(hlt_code, "Unmapped HLT") if hlt_code else "Unmapped HLT"
    hlgt_code = hlt_to_hlgt.get(hlt_code) if hlt_code else None
    hlgt_desc = hlgt_names.get(hlgt_code, "Unmapped HLGT") if hlgt_code else "Unmapped HLGT"
    soc_code = hlgt_to_soc.get(hlgt_code) if hlgt_code else None
    soc_desc = soc_names.get(soc_code, "Unmapped SOC") if soc_code else "Unmapped SOC"

    meddra_lookup[term] = {
        'MedDRA_PT_Term': pt_desc,
        'MedDRA_PT_Code': pt_code,
        'MedDRA_HLT_Term': hlt_desc,
        'MedDRA_HLT_Code': hlt_code if hlt_code else '',
        'MedDRA_HLGT_Term': hlgt_desc,
        'MedDRA_HLGT_Code': hlgt_code if hlgt_code else '',
        'MedDRA_SOC_Term': soc_desc,
        'MedDRA_SOC_Code': soc_code if soc_code else '',
        'MedDRA_Match_Method': method
    }

print(f"\n6. SAVING UNIQUE EVENTS FILE...")
unique_events_df = pd.DataFrame([
    {'Adverse Event': term, **meddra_lookup[term]}
    for term in coding_results.keys()
])
unique_events_df = unique_events_df.sort_values(by='Adverse Event')
unique_events_df.to_excel(UNIQUE_EVENTS_FILE, index=False)
print(f"   ✅ Saved {len(unique_events_df)} unique coded events")

# STRATEGIC DOWNLOAD: Unique events file
try:
    from google.colab import files
    file_size_mb = os.path.getsize(UNIQUE_EVENTS_FILE) / (1024 * 1024)
    print(f"\n   📥 STRATEGIC DOWNLOAD: Unique events file ({file_size_mb:.1f} MB)")
    files.download(UNIQUE_EVENTS_FILE)
    print(f"   ✅ Downloaded! This is your MedDRA coding dictionary.")
except:
    pass

print(f"\n7. MERGING TO ALL EVENTS...")
for event in all_events:
    event_term = event['Adverse Event']
    if event_term in meddra_lookup:
        event.update(meddra_lookup[event_term])

print(f"\n8. CREATING FINAL OUTPUT...")
final_df = pd.DataFrame(all_events)
priority_cols = ['Reference Date', 'Date Added', 'Brand_Name', 'Adverse Event', 'Event_Source', 'inn', 'name']
atc_cols = [f'ATC_Level_{i}_{s}' for i in range(1,6) for s in ['Code', 'Desc']]
meddra_cols = ['MedDRA_PT_Term', 'MedDRA_PT_Code', 'MedDRA_HLT_Term', 'MedDRA_HLT_Code',
               'MedDRA_HLGT_Term', 'MedDRA_HLGT_Code', 'MedDRA_SOC_Term', 'MedDRA_SOC_Code', 'MedDRA_Match_Method']

existing_p = [c for c in priority_cols if c in final_df.columns]
existing_a = [c for c in atc_cols if c in final_df.columns]
existing_m = [c for c in meddra_cols if c in final_df.columns]
remaining = [c for c in final_df.columns if c not in existing_p and c not in existing_a and c not in existing_m]

final_df = final_df[existing_p + existing_a + existing_m + remaining]
final_df = final_df.sort_values(by=['Brand_Name', 'Event_Source', 'Date Added', 'Adverse Event'])
final_df.to_excel(OUTPUT_FILE, index=False)

print("\n" + "="*80)
print("✅ SUCCESS! ULTRA-OPTIMIZED ANALYSIS COMPLETE")
print("="*80)
print(f"\n📊 Optimization Summary:")
print(f"   • SOC filtering reduced search space by {avg_reduction:.1f}%")
print(f"   • Coded {len(coding_results)} unique events")
print(f"   • Applied to {len(all_events)} total events")
print("="*80)

# FINAL DOWNLOADS
print("\n📥 DOWNLOADING OUTPUT FILES...")

files_to_download = [
    (OUTPUT_FILE, "Complete dataset with all events"),
    (UNIQUE_EVENTS_FILE, "Unique events coding dictionary"),
]

try:
    from google.colab import files

    for filepath, description in files_to_download:
        if os.path.exists(filepath):
            file_size_mb = os.path.getsize(filepath) / (1024 * 1024)
            print(f"\n   📄 {description}")
            print(f"      File: {filepath} ({file_size_mb:.2f} MB)")
            print(f"      Downloading...", end=' ')
            files.download(filepath)
            print(f"✅")

    print(f"\n✅ All files downloaded successfully!")
    print(f"\n💡 TIP: If runtime disconnects:")
    print(f"   1. Re-upload checkpoint files (*.pkl)")
    print(f"   2. Set: resume_from_checkpoint = True")
    print(f"   3. Re-run script to continue where you left off")

except ImportError:
    print("\n💡 Not in Colab environment - files saved locally")
except Exception as e:
    print(f"\n⚠️  Download issue: {e}")
    print(f"   Files are saved in Colab - use file browser to download manually")


    
# ════════════════════════════════════════════════════════════════════════════
#  CELL 12 ── PIPELINE WALKTHROUGH: 2 worked examples (mock MedDRA)
#
#  Paracetamol → Diabetic retinopathy   (Exact Match  / 1-SOC path)
#  Paracetamol → Hair thinning and loss (SOC-Filtered / 2-SOC path)
#
#  Self-contained — no API key or MedDRA files required.
# ════════════════════════════════════════════════════════════════════════════

import textwrap, re
from collections import defaultdict

# ── No colour — plain text only ──────────────────────────────────────────────
R   = ""
B   = ""
DIM = ""
WHITE  = ""
LBLUE  = ""
LCYAN  = ""
LGREEN = ""
YELLOW = ""
LRED   = ""
MGNT   = ""
GREY   = ""
BG_NAVY  = ""
BG_TEAL  = ""

def _vis(s):
    return len(re.sub(r'\033\[[0-9;]*m', '', s))

def _pad(s, w, align='left'):
    d = w - _vis(s)
    return (s + ' '*max(0,d)) if align == 'left' else (' '*max(0,d) + s)

W = 76   # total box width

# ── UI primitives ─────────────────────────────────────────────────────────────

def banner(lines, bg=BG_NAVY):
    print(f"{bg}{WHITE}{'▀'*W}{R}")
    for ln in lines:
        print(f"{bg}{WHITE}  {_pad(ln, W-2)}{R}")
    print(f"{bg}{WHITE}{'▄'*W}{R}")

def step_banner(n, title, color=LCYAN):
    num   = f"{BG_TEAL}{WHITE}{B} STEP {n} {R}"
    ttl   = f"{B}{color} {title}{R}"
    fill  = W - _vis(num) - _vis(ttl) - 2
    print(f"\n{num}{ttl}{GREY}{'─'*max(0,fill)}{R}")

def section_rule(label, color=YELLOW):
    s    = f"  {B}{color}{label}{R}  "
    vis  = _vis(s)
    lp   = (W - vis) // 2
    rp   = W - vis - lp
    print(f"\n{GREY}{'╌'*lp}{R}{s}{GREY}{'╌'*rp}{R}")

def hbox(rows, title=None, tc=LCYAN):
    """
    Bordered box.
    Each row is either:
      - ''           → blank line
      - '---'        → horizontal separator
      - str          → plain text (auto-wrapped to inner width)
      - (k,v)        → key│value row  (optionally (k,v,kcol,vcol))
    """
    inner = W - 4

    # ── top border ────────────────────────────────────────────────────────
    if title:
        ts   = f" {B}{tc}{title}{R} "
        tv   = _vis(ts)
        lp   = (W - tv) // 2
        rp   = W - tv - lp
        print(f"{GREY}┌{'─'*lp}{R}{ts}{GREY}{'─'*rp}┐{R}")
    else:
        print(f"{GREY}┌{'─'*(W-2)}┐{R}")

    for row in rows:
        # separator
        if row == '---':
            print(f"{GREY}├{'─'*(W-2)}┤{R}")
            continue
        # blank
        if row == '':
            print(f"{GREY}│{' '*(W-2)}│{R}")
            continue
        # plain string
        if isinstance(row, str):
            for chunk in (textwrap.wrap(row, inner) or ['']):
                print(f"{GREY}│{R}  {_pad(chunk, inner)}  {GREY}│{R}")
            continue
        # key-value tuple
        k, v       = row[0], row[1]
        kc         = row[2] if len(row) > 2 else GREY
        vc         = row[3] if len(row) > 3 else WHITE
        KW         = 22      # key column visible width
        ks         = f"{DIM}{kc}{k}{R}"
        vs         = f"{vc}{v}{R}"
        gap        = inner - KW - 3
        kpart      = _pad(ks, KW + len(ks) - _vis(ks), align='right')
        vpart      = _pad(vs, gap + len(vs) - _vis(vs))
        print(f"{GREY}│{R}  {kpart}  {GREY}│{R}  {vpart}  {GREY}│{R}")

    print(f"{GREY}└{'─'*(W-2)}┘{R}")

def progress_bar(label, value, maximum, bw=22, lw=38):
    filled = int(bw * value / maximum) if maximum else 0
    bar    = f"{LGREEN}{'█'*filled}{GREY}{'░'*(bw-filled)}{R}"
    pct    = 100 * value / maximum if maximum else 0
    ls     = f"{GREY}{label}{R}"
    print(f"  {_pad(ls, lw + len(ls) - _vis(ls))} [{bar}]  "
          f"{WHITE}{value:>3}{GREY}/{maximum}  {YELLOW}{pct:.0f}%{R}")

# ── Mock MedDRA ───────────────────────────────────────────────────────────────
MOCK_PT_DICT = {
    # Eye disorders
    "DIABETIC RETINOPATHY":  ("10012636","Retinal disorders","Posterior eye disorders","Eye disorders"),
    "RETINAL HAEMORRHAGE":   ("10038897","Retinal disorders","Posterior eye disorders","Eye disorders"),
    "MACULAR DEGENERATION":  ("10025421","Retinal disorders","Posterior eye disorders","Eye disorders"),
    "VISION BLURRED":        ("10047531","Visual acuity reduced","Ocular functional conditions","Eye disorders"),
    "PHOTOPHOBIA":           ("10034960","Ocular sensory conditions NEC","Ocular sensory conditions","Eye disorders"),
    # Skin & subcutaneous
    "ALOPECIA":              ("10001781","Alopecia and hair texture abnormalities","Skin appendage conditions","Skin and subcutaneous tissue disorders"),
    "ALOPECIA AREATA":       ("10001783","Alopecia and hair texture abnormalities","Skin appendage conditions","Skin and subcutaneous tissue disorders"),
    "HAIR LOSS ABNORMAL":    ("10018561","Alopecia and hair texture abnormalities","Skin appendage conditions","Skin and subcutaneous tissue disorders"),
    "RASH":                  ("10037844","Rashes NEC","Epidermal and dermal conditions","Skin and subcutaneous tissue disorders"),
    "PRURITUS":              ("10037087","Pruritus NEC","Epidermal and dermal conditions","Skin and subcutaneous tissue disorders"),
    # Endocrine (2nd SOC for scenario B)
    "HYPOTHYROIDISM":        ("10021114","Thyroid gland disorders","Thyroid gland disorders","Endocrine disorders"),
    "ADRENAL INSUFFICIENCY": ("10001335","Adrenal gland disorders","Adrenal gland disorders","Endocrine disorders"),
    "HYPERANDROGENISM":      ("10069382","Androgen related disorders","Sex hormone disorders","Endocrine disorders"),
    # Irrelevant SOCs — demonstrate filtering power
    "HEPATITIS":             ("10019717","Hepatitis NEC","Hepatic disorders","Hepatobiliary disorders"),
    "JAUNDICE":              ("10023126","Cholestasis and jaundice NEC","Hepatic disorders","Hepatobiliary disorders"),
    "HEADACHE":              ("10019211","Headaches NEC","Headaches","Nervous system disorders"),
    "DIZZINESS":             ("10013573","Dizziness","Vertigo and labyrinthine disorders","Nervous system disorders"),
    "PALPITATIONS":          ("10033557","Heart rate and rhythm conditions NEC","Cardiac arrhythmias","Cardiac disorders"),
    "NAUSEA":                ("10028813","Nausea and vomiting","Gastrointestinal signs and symptoms","Gastrointestinal disorders"),
}

mock_soc_to_pts = defaultdict(list)
for pt,(code,hlt,hlgt,soc) in MOCK_PT_DICT.items():
    mock_soc_to_pts[soc].append(pt)
ALL_SOCS       = sorted(mock_soc_to_pts.keys())
TOTAL_PT_SPACE = len(MOCK_PT_DICT)

# ── Pipeline (mirrors real notebook) ─────────────────────────────────────────
def step1_exact_match(t):   return t.upper().strip() in MOCK_PT_DICT

def step2_soc_prediction(t):
    return {"Diabetic retinopathy":   ["Eye disorders"],
            "Hair thinning and loss": ["Skin and subcutaneous tissue disorders",
                                       "Endocrine disorders"]}.get(t, ALL_SOCS)

def step3_filter_pts(socs):
    out=[]
    for s in socs: out.extend(mock_soc_to_pts.get(s,[]))
    return out

def step4_best_pt(t, cands):
    best = {"Diabetic retinopathy":"DIABETIC RETINOPATHY",
            "Hair thinning and loss":"ALOPECIA"}.get(t)
    return best if (best and best in cands) else (cands[0] if cands else None)

def step5_hierarchy(pt):
    return MOCK_PT_DICT.get((pt or "").upper())

# ── Multiaxiality demo ────────────────────────────────────────────────────────
# In the real pipeline the linkage tables are loaded with dict(zip(...)).
# A dict cannot hold duplicate keys, so when the same PT appears under
# multiple HLT → HLGT → SOC paths, only the LAST entry in the .asc file
# survives.  We reproduce that here by deliberately inserting ALOPECIA
# under a secondary SOC first, then under its primary SOC second — the
# final dict therefore retains the primary SOC, mirroring the real behaviour.

MULTIAXIAL_RAW = [
    # (pt_name, pt_code, hlt, hlgt, soc)  — order matters: last entry wins
    ("ALOPECIA", "10001781", "Alopecia and hair texture abnormalities",
     "Skin appendage conditions", "Endocrine disorders"),           # secondary  (loaded first)
    ("ALOPECIA", "10001781", "Alopecia and hair texture abnormalities",
     "Skin appendage conditions", "Skin and subcutaneous tissue disorders"),  # primary (loaded last → survives)
]

# Simulate dict(zip(...)) deduplication — last write wins
pt_to_soc_raw   = {}   # key = pt_name, value = soc
pt_to_soc_steps = []   # log every write so we can display the overwrite
for pt_name, code, hlt, hlgt, soc in MULTIAXIAL_RAW:
    prev = pt_to_soc_raw.get(pt_name)
    pt_to_soc_raw[pt_name] = soc
    pt_to_soc_steps.append((pt_name, soc, prev))

# ══════════════════════════════════════════════════════════════════════════════
EXAMPLES = [
    {"drug":"Paracetamol","ae":"Diabetic retinopathy",
     "label":"SCENARIO A  ·  Single-SOC  ·  Exact Match path"},
    {"drug":"Paracetamol","ae":"Hair thinning and loss",
     "label":"SCENARIO B  ·  Multi-SOC  ·  SOC-Filtered Match path"},
]

print()
banner([
    f"{B}PIPELINE WALKTHROUGH — MedDRA Mapping{R}{WHITE}",
    "Two worked examples  ·  Mock MedDRA  ·  DeepSeek V3 (oracle-simulated)",
    f"{DIM}Mock dictionary: {TOTAL_PT_SPACE} PTs / {len(mock_soc_to_pts)} SOCs"
    f"    (real pipeline: ~26 000 PTs / 27 SOCs){R}{WHITE}",
])

for ex in EXAMPLES:
    drug, ae = ex["drug"], ex["ae"]
    print()
    banner([
        f"{B}{ex['label']}{R}{WHITE}",
        f"Drug: {B}{drug}{R}{WHITE}   ·   LLM-extracted AE: {B}« {ae} »{R}{WHITE}",
    ], bg=BG_TEAL)

    # ── STEP 1 ────────────────────────────────────────────────────────────────
    step_banner(1, "Exact String Match", LCYAN)
    exact = step1_exact_match(ae)
    hbox([
        ("Input term",  ae.upper(), GREY, WHITE),
        ("Dictionary",  f"{TOTAL_PT_SPACE}-term MedDRA v28 PT list (case-insensitive)", GREY, GREY),
        "---",
        ("Result",
         f"{LGREEN}{B}✔  MATCH FOUND{R}  — assigned as 'Exact Match'" if exact
         else f"{LRED}{B}✘  No exact match{R}  — proceed to SOC-filtered search",
         GREY, WHITE),
        ("Next",
         f"{LGREEN}Pipeline ends here for this term.{R}" if exact
         else f"{YELLOW}→  Steps 2 · 3 · 4  required{R}",
         GREY, WHITE),
    ])

    if exact:
        best_pt, result_method, pred_n = ae.upper(), "Exact Match", 1
    else:
        # ── STEP 2 ────────────────────────────────────────────────────────────
        step_banner(2, "LLM Predicts Likely SOC(s)", MGNT)
        pred_socs = step2_soc_prediction(ae)
        n_soc     = len(pred_socs)
        path_tag  = (f"{LGREEN}1-SOC path  →  narrow candidate pool{R}" if n_soc == 1
                     else f"{YELLOW}Multi-SOC path  →  {n_soc} SOCs  →  broader pool{R}")
        hbox([
            ("Input",  f"'{ae}'  +  full list of 27 MedDRA SOCs", GREY, WHITE),
            ("Output", "  ·  ".join(f"{YELLOW}{s}{R}" for s in pred_socs), GREY, WHITE),
            ("Path",   path_tag, GREY, WHITE),
            "---",
            f"{GREY}⚠  SOC predictions are used {B}only as a search filter{R}{GREY}.{R}",
            f"{GREY}   They are {B}NOT{R}{GREY} stored as the final SOC annotation.{R}",
        ], title="LLM — SOC Prediction", tc=MGNT)

        # ── STEP 3 ────────────────────────────────────────────────────────────
        step_banner(3, "Filter PT Candidate Space", LCYAN)
        candidates = step3_filter_pts(pred_socs)
        n_cand     = len(candidates)
        excluded   = TOTAL_PT_SPACE - n_cand

        print(f"\n  {GREY}Full dictionary:{R}  {B}{WHITE}{TOTAL_PT_SPACE}{R} PTs"
              f"  across  {B}{WHITE}{len(ALL_SOCS)}{R} SOCs")
        print(f"  {GREY}Predicted SOC(s):{R}  ",
              "   ".join(f"{YELLOW}{s}{R}" for s in pred_socs))
        print()
        for s in pred_socs:
            progress_bar(s, len(mock_soc_to_pts[s]), TOTAL_PT_SPACE)
        print(f"  {GREY}{'─'*60}{R}")
        progress_bar("COMBINED CANDIDATE POOL", n_cand, TOTAL_PT_SPACE)
        print()

        hbox(
            [f"  {LGREEN}+{R}  {WHITE}{pt}{R}" for pt in candidates]
            + [f"  {LRED}−{R}  {GREY}[{excluded} terms from "
               f"{len(ALL_SOCS)-len(pred_socs)} other SOCs excluded]{R}",
               "",
               f"{YELLOW}{B}Search space: {TOTAL_PT_SPACE} → {n_cand} PTs  "
               f"({100*(1-n_cand/TOTAL_PT_SPACE):.0f}% reduction){R}"],
            title="Candidate PT Pool after SOC Filtering", tc=LCYAN)

        # ── STEP 4 ────────────────────────────────────────────────────────────
        step_banner(4, "LLM Selects Single Best-Matching PT", MGNT)
        best_pt   = step4_best_pt(ae, candidates)
        near_note = (f"{LGREEN}Exact string in candidates{R}" if ae.upper() in candidates
                     else f"{YELLOW}Near-match:  '{ae}'  →  '{best_pt}'{R}")
        hbox([
            ("Input",      f"'{ae}'  +  {n_cand} filtered candidates", GREY, WHITE),
            ("LLM picks",  f"'{best_pt}'", GREY, LGREEN),
            ("Match type", near_note,      GREY, WHITE),
            ("Validation", f"'{best_pt}' found in PT dictionary  {LGREEN}✔  OK{R}", GREY, WHITE),
            ("Method flag", f"{LCYAN}SOC-Filtered Match{R}", GREY, WHITE),
            "---",
            f"{GREY}If the LLM returns a non-existent PT name, the code attempts a fuzzy{R}",
            f"{GREY}lookup. Persistent failures are flagged {LRED}'No Match'{R}{GREY} for manual{R}",
            f"{GREY}review — they are {B}never silently dropped{R}{GREY}.{R}",
        ], title="LLM — Best-PT Selection", tc=MGNT)

        result_method, pred_n = "SOC-Filtered Match", n_soc

    # ── STEP 5 ────────────────────────────────────────────────────────────────
    step_banner(5, "Resolve Full MedDRA Hierarchy  (deterministic — no LLM)", LGREEN)
    pt_code, hlt, hlgt, final_soc = step5_hierarchy(best_pt)

    # ── Show multiaxiality resolution for Alopecia scenario only ─────────────
    if best_pt == "ALOPECIA":
        section_rule("MedDRA MULTIAXIALITY — how SOC is resolved by dict construction", YELLOW)
        print()
        print(f"  {GREY}ALOPECIA belongs to {YELLOW}{B}2 SOCs{R}{GREY} in MedDRA (multi-axial).{R}")
        print(f"  {GREY}The pipeline loads linkage tables with {LCYAN}dict(zip(...)){R}"
              f"{GREY} — last entry wins:{R}")
        print()
        for i, (pt_name, soc, prev) in enumerate(pt_to_soc_steps):
            order = f"{GREY}entry {i+1}{R}"
            if prev is None:
                status = f"{YELLOW}written   →  pt_to_soc['{pt_name}'] = '{soc}'{R}"
            else:
                status = (f"{LRED}overwrite{R}  →  "
                          f"{GREY}'{prev}'{R} {LRED}discarded{R}  "
                          f"{LGREEN}'{soc}' retained{R}")
            print(f"  {order}  {status}")
        print()
        print(f"  {GREY}Result: the surviving entry is whichever SOC appears {B}last{R}"
              f"{GREY} in the .asc file.{R}")
        print(f"  {YELLOW}⚠  This is implicit — the code does not read a 'primary SOC' flag.{R}")
        print(f"  {YELLOW}   It relies on MedDRA file ordering being stable across versions.{R}")
        print()

    hbox([
        ("Confirmed PT", f"{B}{best_pt.title()}{R}  {GREY}(code: {pt_code}){R}", GREY, WHITE),
        "",
        f"  {LCYAN}{B}PT{R}    ──▶   {WHITE}{best_pt.title()}{R}",
        f"  {LCYAN}{B}HLT{R}   ──▶   {WHITE}{hlt}{R}",
        f"  {LCYAN}{B}HLGT{R}  ──▶   {WHITE}{hlgt}{R}",
        f"  {LGREEN}{B}SOC{R}   ──▶   {LGREEN}{B}{final_soc}{R}"
        f"   {DIM}◄── FINAL  (last-loaded linkage entry){R}",
        "",
        "---",
        f"{GREY}Traversal uses MedDRA ASCII linkage tables — no LLM at this stage.{R}",
        "",
        f"{B}Key point:{R}  Even though {YELLOW}{B}{pred_n}{R} SOC(s) were used as a filter,",
        f"exactly {LGREEN}{B}ONE{R} SOC is written to the final record.",
        f"It is the last-loaded linkage entry for this PT in the .asc files,",
        f"not an explicit primary-SOC lookup. Secondary memberships are discarded.",
    ], title="Hierarchy Traversal  PT → HLT → HLGT → SOC", tc=LGREEN)

    # ── Output record ─────────────────────────────────────────────────────────
    section_rule("OUTPUT ROW  —  written to Excel dataset", YELLOW)
    print()
    hbox([
        ("Drug",               drug,                      GREY, WHITE),
        ("LLM_extracted_AE",   ae,                        GREY, YELLOW),
        ("MedDRA_PT_Term",     best_pt.title(),            GREY, WHITE),
        ("MedDRA_PT_Code",     pt_code,                    GREY, GREY),
        ("MedDRA_HLT_Term",    hlt,                        GREY, GREY),
        ("MedDRA_HLGT_Term",   hlgt,                       GREY, GREY),
        ("MedDRA_SOC_Term",    final_soc,                  GREY, LGREEN+B),
        ("MedDRA_Match_Method",result_method,              GREY, LCYAN),
    ])

# ══════════════════════════════════════════════════════════════════════════════
#  SIDE-BY-SIDE COMPARISON
# ══════════════════════════════════════════════════════════════════════════════
print()
banner([f"{B}SIDE-BY-SIDE COMPARISON{R}{WHITE}"])

n_cands_b = len(step3_filter_pts(step2_soc_prediction("Hair thinning and loss")))
CW = 28
rows_cmp = [
    ("Aspect",                   f"{LCYAN}{B}Scenario A{R}",         f"{YELLOW}{B}Scenario B{R}"),
    ("─"*26,                     "─"*26,                             "─"*26),
    ("LLM extracted term",       "Diabetic retinopathy",             "Hair thinning and loss"),
    ("Step 1 exact match",       f"{LGREEN}YES  → stops here{R}",   f"{LRED}NO   → continues{R}"),
    ("LLM calls (total)",        "1  (extraction only)",             "3  (extract + SOC + PT)"),
    ("SOCs predicted",           f"{GREY}N/A{R}",                    f"{YELLOW}2  (Skin + Endocrine){R}"),
    ("Candidate PT pool",        f"{GREY}N/A  (full dict){R}",       f"{YELLOW}{n_cands_b} / {TOTAL_PT_SPACE} PTs  (58% ↓){R}"),
    ("PT assigned",              "Diabetic Retinopathy",             "Alopecia"),
    ("Final SOC",                "Eye disorders",                    "Skin and subcut. disorders"),
    ("Match method",             f"{LCYAN}Exact Match{R}",          f"{LCYAN}SOC-Filtered Match{R}"),
    ("SOCs in final record",     f"{LGREEN}{B}1{R}",                f"{LGREEN}{B}1{R}"),
]
print()
for label, a, b in rows_cmp:
    lw = max(28, _vis(label))
    print(f"  {_pad(label, lw)}  {_pad(a, CW + len(a) - _vis(a))}  {b}")

# ══════════════════════════════════════════════════════════════════════════════
#  KEY TAKE-AWAYS
# ══════════════════════════════════════════════════════════════════════════════
print()
banner([f"{B}KEY TAKE-AWAYS{R}{WHITE}"])
print()

takeaways = [
    (LCYAN,  "1", "SOC prediction (Step 2) is a search heuristic only.",
                  "It does NOT determine the final SOC annotation."),
    (LGREEN, "2", "Regardless of how many SOCs the LLM predicts, the final record",
                  f"always carries exactly {B}ONE{R} primary SOC — set by the MedDRA hierarchy."),
    (YELLOW, "3", "Near-matches (e.g. 'Hair thinning and loss' → 'Alopecia') are resolved",
                  f"by Step 4 but introduce semantic ambiguity.  Flag via {LCYAN}MedDRA_Match_Method{R}."),
    (MGNT,   "4", f"Scenario A: {LGREEN}faster{R} (1 LLM call), unambiguous.",
                  f"Scenario B: {YELLOW}slower{R} (3 LLM calls), higher mapping uncertainty."),
]
for color, n, *lines in takeaways:
    print(f"  {BG_TEAL}{WHITE}{B} {n} {R}  {B}{color}{lines[0]}{R}")
    for ln in lines[1:]:
        print(f"       {ln}")
    print()

print(f"{DIM}  Walkthrough complete.{R}\n")
